### ISSUE TITLE
Feature Request: Support Menu inside overflow parent containers

### ISSUE THREAD

**Issue by mrudowski** [szhsin/react-menu#10]
Hello,

I really like this lib: code, docs and examples. 
When I've found it some time ago I was delighted (even after used reactstrap and antd multi level dropdown)
So good you share it.

But what I observed now the menu is rendered direct in DOM, direct below its trigger.
Without any js/react popper or react portals it cannot force through overflow parents container
(the ones with  `overflow: hidden; position: relative;`)

I hope you will find the way.
I will keep my fingers crossed.

**Comment by szhsin** [comment]
Hi @mrudowski ,

Thanks for your feedback and appreciation of the project.
Support for menu positioning against a parent container (and overflow) is indeed a feature I plan to add in a future release.

You mentioned menu is rendered below the trigger in DOM, just wanting to get some clarification for your requirements.
Because menu is absolutely positioned, the place where it's rendered in DOM should be irrelevant in this matter.

**Comment by mrudowski** [comment]
I think the place in DOM will be important if you plan to add support for menu positioning against/through an overflow parent container.
Then the menu will probably will be attached to the end of document body (using react popper and/or react portals)

All the best to you!

**Comment by szhsin** [comment]
Do you want to implement something similar to [this example](https://codesandbox.io/s/overflow-parent-l387b)?

**Comment by mrudowski** [comment]
In many cases we need that dropdown "pop up" from the overflow relative container, but as you can see here it can't

https://codesandbox.io/s/overflow-parent-forked-lymy8?file=/src/App.js

**Comment by szhsin** [comment]
Ah~, you need the menu to break out from its parent, I think portal is the answer. 
It'll be added in an upcoming release, pls stay tuned, cheers!

**Comment by szhsin** [comment]
Hi @mrudowski,  the portal feature is released in [v1.2.0](https://github.com/szhsin/react-menu/releases/tag/v1.2.0). Thanks for reporting the issue.

**Comment by mrudowski** [comment]
Thank you @szhsin
