### ISSUE TITLE
SubMenu positioning

### ISSUE THREAD

**Issue by liviuclement** [szhsin/react-menu#1046]
Hello!

I have a use case where I need to align a submenu (relative to the trigger MenuItem) starting from top when it fits into the screen (the default behaviour) and from the bottom when it doesn't, rather than pushing it a few pixels upwards (the behaviour I'm looking for). Is this implemented and if not, can it be added as a feature?

This is the behaviour right now:

![Screenshot 2023-08-15 at 12 04 56](https://github.com/szhsin/react-menu/assets/50109970/db3c86d1-b77b-4d45-a119-126b4b6b7b89)
![Screenshot 2023-08-15 at 12 02 11](https://github.com/szhsin/react-menu/assets/50109970/c4b83a47-7f14-4ce9-96ca-ee8226f890d9)

This is what I'm looking  for:
![Screenshot 2023-08-15 at 12 04 56](https://github.com/szhsin/react-menu/assets/50109970/db3c86d1-b77b-4d45-a119-126b4b6b7b89)
![Screenshot 2023-08-15 at 12 01 42](https://github.com/szhsin/react-menu/assets/50109970/056f6661-d068-4392-9c59-dd4c1fe7c048)

*For clarification, in the second picture for each case, the bottom of the screenshot is where the bottom of the window was at.

React/React-dom version: 17.0.2
React-Menu version: 3.2.1

**Comment by szhsin** [comment]
Hi @liviuclement , it was not implemented. The currently behaviour is the same as many submenu implementations. 

For example, here is the native macOS menu:
<img width="356" alt="Screen Shot 2023-08-23 at 10 27 13 pm" src="https://github.com/szhsin/react-menu/assets/41896553/a4bcf024-c248-4e9d-81aa-ad61f05d5483">

When it cannot fit into screen from the bottom:
<img width="356" alt="Screen Shot 2023-08-23 at 10 27 32 pm" src="https://github.com/szhsin/react-menu/assets/41896553/755dbe10-811c-4b2e-810d-88f6cc4bafe7">

I'm curious to understand the rationale you wish to have a different behaviour.

**Comment by szhsin** [comment]
You may try to set the `shift` prop which adjusts alignment of menu with its anchor element. https://szhsin.github.io/react-menu#menu-placement

Not sure your exact use case, but eventually there could be some JavaScript required in the user space to apply relevant props under different conditions.

**Comment by szhsin** [comment]
Closing this issue as the current behaviour aligns with native OS menus, and there are no real benefits or use cases to implement it differently.
