### ISSUE TITLE
Make required peerDependencies explicit in the README

### ISSUE THREAD

**Issue by moroshko** [szhsin/react-menu#105]
The readme says:
> No peer dependency is required except React 16.8+.

But, [`package.json` has `prop-types` in `peerDependencies`](https://github.com/szhsin/react-menu/blob/e8caed0675e1fb67350f48d9a172f8f71c6eeb07/package.json#L35), and indeed I get this:
> warning " > @szhsin/react-menu@1.9.0" has unmet peer dependency "prop-types@>=15.7.2".

**Comment by szhsin** [comment]
Hi @moroshko , thanks for the feedback.
This sentence has been removed from README, and to be published in `npm` along with next release.
