### ISSUE TITLE
How to implement Slide-in/out behavior 

### ISSUE THREAD

**Issue by ruchiaa** [szhsin/react-menu#1076]
How can I use this to implement the slide-in/out behavior for a side bar menu? Something like the slide in-out displayed here: https://react-responsive-multi-level-menu-demo.netlify.app/

**Comment by szhsin** [comment]
Unfortunately we don't support submenus like in your example link. 

The submenu of this package has a similar behaviour to native OS menus: a parent menu stays on the screen after a submenu has opened from it.

In the example, a submenu menu replaces the parent menu in place after being opened. This is a quite different implementation and would not be supported by the package.
