### ISSUE TITLE
SubMenu transition

### ISSUE THREAD

**Issue by ruchiaa** [szhsin/react-menu#1077]
How to support submenu transition animation? I see that Menu and ControlledMenu do have transition property, but SubMenu does not.

**Comment by szhsin** [comment]
Hey @ruchiaa , submenu transition animation is controlled by the [`transition`](https://github.com/szhsin/react-menu/blob/4a2966d52f5f36705f602c0418e92926968ad614/types/index.d.ts#L143) prop on the root menu component (either a Menu or ControlledMenu).

All the submenus on docs website have animation enabled: https://szhsin.github.io/react-menu#submenu

You could also check the styled sandbox examples: https://szhsin.github.io/react-menu#styling
