### ISSUE TITLE
Conditionally use click vs hover as the trigger for a ControlledMenu and SubMenu

### ISSUE THREAD

**Issue by ruchiaa** [szhsin/react-menu#1078]
I want to use click to trigger the ControlledMenu and its SubMenus if some condition is true, and hover otherwise. How can I achieve this?

**Comment by szhsin** [comment]
Here is a [sandbox example](https://codesandbox.io/s/react-menu-1078-h2h9n9?file=/src/App.js) for your use case.

It uses both `useClick` and `useHover` from the package, and a boolean toggle to conditionally apply props to the `ControlledMenu`.

For submenu, it has an [`openTrigger`](https://github.com/szhsin/react-menu/blob/4a2966d52f5f36705f602c0418e92926968ad614/types/index.d.ts#L479) prop which controls whether the menu is triggered by click or hover events.

**Comment by ruchiaa** [comment]
That works! Thank you!
