### ISSUE TITLE
Menu does not stay anchored to button when portal=true

### ISSUE THREAD

**Issue by nmanandhar** [szhsin/react-menu#110]
![bug](https://user-images.githubusercontent.com/9746042/113592682-2dd12580-9655-11eb-94a7-a2ec03a0020a.gif)

**Comment by szhsin** [comment]
Hi @nmanandhar , please see [this example](https://codesandbox.io/s/react-menu-portal-scroll-close-p273g) for a solution to this issue. In your use case, it looks like the container is being resized and you might need to use an `ResizeObserver`.

**Comment by nmanandhar** [comment]
Closing the menu when container is resized is an acceptable solution for my case

**Comment by jhrinoa** [comment]
It looks like repositionFlag prop works great.
Here's an [example](https://codesandbox.io/s/react-menu-portal-resize-reposition-twd2f?file=/src/App.js)
