### ISSUE TITLE
Fixed position elements in long scrolling menus?

### ISSUE THREAD

**Issue by gang-qiu-social-chorus** [szhsin/react-menu#111]
Hi there,

I was wondering if it is possible to have the dropdowns render a fixed button or view at the top or bottom of the menu? I know that there are `<FocusableItem>` that can be an input or button that can be placed anywhere in the menu, but when a list is long and scrolling occurs, is it possible to "fix" these items to the top or bottom? See this codesandbox. https://codesandbox.io/s/youthful-bush-v1fu8?file=/src/App.js

**Comment by szhsin** [comment]
Hi @gang-qiu-social-chorus, currently it's not possible to have nested scroll view within a menu list. This is indeed a valid use case and will be supported in a coming release.

**Comment by gang-qiu-social-chorus** [comment]
that will be a tremendously useful addition!

**Comment by szhsin** [comment]
Feature released in [v1.10.0](https://github.com/szhsin/react-menu/releases/tag/v1.10.0), please refer to the [example](https://szhsin.github.io/react-menu/#menu-overflow) and [docs](https://szhsin.github.io/react-menu/docs#menu-group). @gang-qiu-social-chorus

**Comment by gang-qiu** [comment]
This is amazing, thank you!
