### ISSUE TITLE
ControlledMenu keepOpen at top level trigger

### ISSUE THREAD

**Issue by ruchiaa** [szhsin/react-menu#1115]
How can I prevent the top level menu item from closing when the trigger button is clicked again?
For example, this is a snippet of my code. I also looke at the `keepOpen` example you have posted https://codesandbox.io/s/react-menu-keepopen-dzscw?file=/src/App.js:856-888 but I need the top level button to stay open when it is clicked. In the sandbox example, I want the behavior to be such that clicking on "Open Menu" to stay open when it is clicked on again.

```
                            <button
                                {...clickAnchorProps}
                                type="button"
                                ref={ref}
                                ...
                            >
                                <MenuItemDisplay
                                    .....
                                />
                            </button>

                            <ControlledMenu
                                {...menuState}
                                anchorRef={ref}
                                onClose={(closeEvent, value) => {
                                    console.log('closeEvent', closeEvent, value)
                                    toggle(false);
                                }}
                                arrow
                            >
                                ...
                            </ControlledMenu>

```

**Comment by szhsin** [comment]
This is an rather uncommon use case but still achievable using the `ControlledMenu`. In the `onClose` event we can choose not to close menu when it has lost focus. 
```jsx
        onClose={(e) => {
          // Do not close menu after it loses focus by overriding the default implementation
          e.reason !== "blur" && setOpen(false);
        }}
```
Then you will need to manually detect something outside menu is clicked and close it. You can use an npm package such as [react-detect-click-outside](https://www.npmjs.com/package/react-detect-click-outside), or implement it yourself.

Here is an example https://codesandbox.io/s/react-menu-1115-wk7cfv?file=/src/App.js

**Comment by ruchiaa** [comment]
Thank you! That worked
