### ISSUE TITLE
Unhover a Submenu programmatically

### ISSUE THREAD

**Issue by ruchiaa** [szhsin/react-menu#1132]
Can I unhover a submenu programmatically? I have submenus with a button as the label and when a keyboard tab even focuses to another submenu's button label, the previous Submenu remains in hovered state. I'd like to unset the hover state of the previous submenu upon focus of the other submenu's button label.

**Comment by szhsin** [comment]
It would great an example were provided for the issue. Technically only one element can be focused in the DOM, so what you saw might be a hovered state. If that's the case, just simply style it with css so that it looks no different to other items.

**Comment by szhsin** [comment]
Closing stale issue.
