### ISSUE TITLE
Adding closeMenuOnSelect prop

### ISSUE THREAD

**Issue by danielpaz6** [szhsin/react-menu#1133]
Would it be possible to add an attribute `closeMenuOnSelect`, the default would be `true` which means that when something is being selected, the menu will disappear, but if its value is `false`, then that won't be the case and the panel will be available to select more things.

Sometimes users may need to select multiple options and it's annoying to re-open the menu, especially if there are sub-menus.

**Comment by szhsin** [comment]
Hi, the usage is achievable by setting the `keepOpen` in click events. The API provides a finer control per item and per event than having a `closeMenuOnSelect` prop on the menu itself. 

An example demonstrating the basic usage: https://codesandbox.io/s/react-menu-click-event-1p4604
Also here is another example for more advance use cases: https://codesandbox.io/s/react-menu-keepopen-dzscw
