### ISSUE TITLE
menuRef.current is null when ControlledMenu is rendered on a Modal

### ISSUE THREAD

**Issue by manoharrajaram** [szhsin/react-menu#1152]
I am calling `ControlledMenu` inside a Modal component. I get the following error 
`TypeError: Cannot read properties of null (reading 'querySelectorAll')`

The error is coming inside the `useItems.js` 
The weird thing is when I try to debug, menuRef is always initialised and does error out but when I do the same click action without debugger, I get the above error.
```
    var sortItems = function sortItems() {
      if (mutableState.sorted) return;
      var orderedNodes = menuRef.current.querySelectorAll('.szh-menu__item');
      items.sort(function (a, b) {
        return indexOfNode(orderedNodes, a) - indexOfNode(orderedNodes, b);
      });
      mutableState.sorted = true;
    };
```

```
    <ControlledMenu
      ref={ref}
      captureFocus={captureFocus}
      align={align}
      anchorRef={anchorRef}
      className={classes['select-dropdown']}
      direction={direction}
      menuClassName={clsx(className, widthToWidthClass[width])}
      menuItemFocus={{ position: 'first' }}
      onItemClick={handleOnItemClick}
      onKeyDown={redirectToSearchInputHandler}
      portal={true}
    >
    ...
    </ControlledMenu>
```

This problem does not occur when I call the `ControlledMenu` outside of a Modal

**Comment by szhsin** [comment]
This might be related to https://github.com/szhsin/react-menu/issues/1097 which was fixed recently. Please upgrade to [v4.1.0](https://github.com/szhsin/react-menu/releases/tag/v4.1.0) to see if the problem goes away. If not, please provide a sandbox example demonstrating the issue.
