### ISSUE TITLE
how to open submenus at the same level visually?

### ISSUE THREAD

**Issue by ghost** [szhsin/react-menu#1162]
submenu should align with entire parent menu (center or start), not just with the menu item that opens the submenu

![image](https://github.com/szhsin/react-menu/assets/138553763/b7e8036e-d76a-452e-b0d4-0224e15f9ced)

![image](https://github.com/szhsin/react-menu/assets/138553763/66bc68e4-dec4-4a6f-858b-4939dcf3d5c1)

**Comment by szhsin** [comment]
You can achieve it using the `shift` prop on the submenu like this [sandbox example](https://codesandbox.io/p/sandbox/react-menu-1162-4kf5j3?file=%2Fsrc%2FApp.js%3A43%2C31-43%2C42).

**Comment by szhsin** [comment]
Well, this is not a dedicated solution for your requirement. Maybe consider it as a workaround or even a hack. This requirement is very uncommon and not the way how usually menus behaviour in most systems.

When building a reusable library, we have to balance between the features and the complexity they introduce. We won't ship features that are not required by 99% of users, but still increase the size and complexity of the package. I can assure you there probably isn't a menu package in the community has support for this.

**Comment by szhsin** [comment]
@terlan4 , thanks for your support of this project.

I figured out another hacky solution with the advantage that `shift` value is not hardcoded. The solution provides the root menu with a customised [boundingBoxRef](https://github.com/szhsin/react-menu/blob/d7c4df8a4324847403990174d9298038e11ac0c2/types/index.d.ts#L265) prop which constrains all submenus within a boundary. The submenus are given a large negative shift (e.g. -9999). With the default automatic placement behaviour they all align with the anchor button.

See [sandbox example](https://codesandbox.io/p/sandbox/react-menu-1162-b-g34gt3)
