### ISSUE TITLE
how to have focus on item on menu open

### ISSUE THREAD

**Issue by ghost** [szhsin/react-menu#1168]
Hi, I want the focus to be on "Copy" when menu is opened. And clicking Up Arrow key takes me to Cut, or just clicking on "Enter" after menu is opened will do the "Copy" thing. How can I achieve this? Thanks

![image](https://github.com/szhsin/react-menu/assets/138553763/42716f2b-e2a6-4c47-8280-3e32bf395f35)

**Comment by szhsin** [comment]
If you could use the `ControlledMenu`, it has a `menuItemFocus` prop for this use case. [Here is an example.](https://codesandbox.io/p/sandbox/react-menu-1168-tc8st5)
