### ISSUE TITLE
How to allow tooltips on disabled menu items?

### ISSUE THREAD

**Issue by seperman** [szhsin/react-menu#1172]
Hello,
Tooltips work great with MenuItem unless the MenuItem is disabled.
I intend to let the user know why the menu item is disabled using the tooltip.
Can you please explain how that can work?
Thanks!

Example:

```jsx
        <Tooltip
          title='Explain why disabled'
        >
          <MenuItem disabled>Some Menu</MenuItem>
        </Tooltip>
```

**Comment by szhsin** [comment]
A menu item in a disabled state has `aria-disabled="true"`. Apart from that, we haven't done anything particular to change the behaviour. If you have the code below:
```jsx
<MenuItem title="Save to file" disabled>
  Save
</MenuItem>
```
When the menu item is hovered, it will show a default tooltip from the browser.
<img width="175" alt="menu tooltip" src="https://github.com/szhsin/react-menu/assets/41896553/57a6b3c0-f36e-464a-9a11-b4d9b24b0203">

I saw the tooltip from your code was an external component. It could be that component has some mechanism to disable itself when it detects the child element has `aria-disabled="true"`.

**Comment by szhsin** [comment]
Closing stale issue.
