### ISSUE TITLE
Override SUBMENU_OPEN_DELAY

### ISSUE THREAD

**Issue by R4VANG3R** [szhsin/react-menu#118]
Is there a way to set `SUBMENU_OPEN_DELAY`? I'd like there not to be a delay at all.

**Comment by szhsin** [comment]
Hi @R4VANG3R , currently the submenu delays are using pre-defined values. Will add two props that allow them to be configurable.

**Comment by R4VANG3R** [comment]
Nice that would be a big help, especially when using no animations.

**Comment by R4VANG3R** [comment]
Thank you! 🎉
