### ISSUE TITLE
MenuButton: StopPropagation on button click

### ISSUE THREAD

**Issue by Kay2dan** [szhsin/react-menu#1218]
Is there a way to trigger 'stopPropagation' on the 'MenuButton'? 

_**Scenario:**_
I have React-Menu implemented within an Accordion component. 
Currently, When the <MenuButton> is clicked, this triggers the Accordion click handler as well. 

**_Solution sought:_**
When the React-Menu <MenuButton> component is clicked, I want to trigger ev.stopPropagation() to stop the event from propagating up the DOM hierarchy. 

Thank you,

**Comment by szhsin** [comment]
I think the easiest way is to attach an `onClick` handler to menu button and call `stopPropagation` from there:
```jsx
<Menu menuButton={<MenuButton onClick={e => e.stopPropagation()}>Menu</MenuButton>}>
  <MenuItem>Cut</MenuItem>
  <MenuItem>Copy</MenuItem>
  <MenuItem>Paste</MenuItem>
</Menu>
```

**Comment by Kay2dan** [comment]
Resolved as per szhsin's reply.
