### ISSUE TITLE
loading 2000 items is very slow, is there some way to make it faster ?

### ISSUE THREAD

**Issue by liorsaadonpapaya** [szhsin/react-menu#1262]
when trying to load big lists 2000 items opening the menu becomes very slow and the browser get stuck
is there a way to create a virtualization of some kind or another solution to solve the performance issue ?

React/React-dom version: 16.9.8
React-Menu version: 3.3.0

**Comment by szhsin** [comment]
hey @liorsaadonpapaya , tried loading 2000 items in an example and it seems not bad for me. Tested both on a laptop and iPhone device. The delay feels like 100ms-ish. Is there something else in your code that could have impacted the performance?
https://codesandbox.io/p/sandbox/react-menu-1262-dmclw6

**Comment by liorsaadonpapaya** [comment]
sorry, tested again we are talking about 9000+ items
![image](https://github.com/szhsin/react-menu/assets/82823508/7b1574ba-7ec1-4706-ba21-8178ee312268)

on my macbook pro 32gb it works in 2sec

on a slower windows machine with 16gb it is crashing

**Comment by szhsin** [comment]
With such amount of data, we will definitely require virtualisation. Fortunately, the menu integrates nicely with the [react-window](https://github.com/bvaughn/react-window).

[Here is an example](https://codesandbox.io/p/devbox/react-menu-1262-v-96jyp5?file=%2Fsrc%2FApp.tsx) that renders 10000 items without any issue.

**Comment by liorsaadonpapaya** [comment]
thanks, i already implemented a solution with react-window that works great, thanks
