### ISSUE TITLE
Hover over to produce a popup box for hovered text?

### ISSUE THREAD

**Issue by VladParshin** [szhsin/react-menu#130]
I noticed there is a hover option and things you can do, however, is it possible for the hover option, to produce another item that 'pops' out for the entree?

Main use is to have menu items in one language, which, if you hover over, would produce a different box with English text equivalent to that entry?

Is this something that your Menu module could do, or would I have to find a separate way of getting this to work for the MenuItem elements?

Something equivalent to this 
![image](https://user-images.githubusercontent.com/63443061/116669104-86d87300-a9e1-11eb-88f8-c38f775c05b5.png)

**Comment by szhsin** [comment]
Hi @VladParshin , displaying tooltip when hovering on menu items like the above example is part of your application logic and out of scope for this menu library.

As you mentioned the `hover` parameter, it can be helpful in this use case.
I wrote a simple example that demonstrates two ways to implement the tooltip. (just some ideas, you might come with your own method) https://codesandbox.io/s/react-menu-issue-130-tooltip-rywf6

**Comment by VladParshin** [comment]
Much appreciated! Thanks for the example as well :)

**Comment by VladParshin** [comment]
Sorry to re-open the issue. Your solution worked great for MenuItem elements, however, One issue I ran into is that the SubMenu item does not take a DIV element, since it uses a label to produce the sub-menu category's text rather than the way MenuItems generates a div for it's text.
I believe it might be the same case for each of the actual Menu items (the actual top-level button), based on how it is generated.

**Comment by szhsin** [comment]
@VladParshin, you can use the same approach to create tooltips with submenu's `label` and menu's `menuButton` prop. Both of them accept any `React` node or a render prop.

I'v updated the example: https://codesandbox.io/s/react-menu-issue-130-tooltip-rywf6
It's still a rough demo, you might need to refine the UX in production code.

**Comment by VladParshin** [comment]
@szhsin Thanks a lot for the help, I really appreciate it. I've had to re-write some stuff as a class instead of function, and everything works, except for a tiny issue with the SubMenu. 
All Menu items render the tooltip properly based on mouse location and all menuItems render along the whole length of the field.
However, the SubMenu renders only along the part that is text (As I understand, because it is only in the label part).
Example provided below. Mouse location is marked in red (as screenshots don't pick up mouse, sorry)

![image](https://user-images.githubusercontent.com/63443061/116972105-e09cae00-acfd-11eb-9a35-8adf9d214fa8.png)


Code segment

```
import React from 'react';
import {
    Menu,
    MenuItem,
    MenuButton,
    SubMenu, MenuDivider
} from '@szhsin/react-menu';
import '@szhsin/react-menu/dist/index.css'

const tooltipStyle = {
    position: "absolute",
    pointerEvents: "none",
    backgroundColor: "#D7D7A6",
    border: "1px solid",
    padding: "1px 8px",
    whiteSpace: "nowrap",
    zIndex: 200
};

class TopMenuDropdown extends React.Component {

    state = {
        pos: {x:0, y:0},
        tooltip:'',
        show:false
    };

    createTooltip = (tooltip) => ({
        onMouseEnter: ({ clientX, clientY}) => {
            console.log ('Mouse Entering');
            this.setState (
                {
                    pos: {x:clientX, y:clientY},
                    tooltip: tooltip,
                    show: true
                }
            );
        },
        onMouseLeave: () => {
            console.log ('Mouse Leaving');
            this.setState(
                {
                    show:false
                }
            )
        }
    });

    handleSelect = ({value}) => {
        this.props.onClick(value);
    }

    renderMenuItem (menuAnchor, menuItems, isSubMenu) {
        if (isSubMenu) {
            return (
                <SubMenu key={menuAnchor.id}
                            label={
                                <div
                                    {...this.createTooltip(menuAnchor.attributes.title)}
                                >
                                    {menuAnchor['#text']}
                                </div>
                            }
                >
                    {this.menuGeneration(menuItems,menuAnchor)}
                </SubMenu>
            );
        }

        return (
            <>
            <Menu
                style={{display: 'flex', float: 'left'}}
                key={menuAnchor.id}
                menuButton={<MenuButton {...this.createTooltip(menuAnchor.attributes.title)}>{menuAnchor['#text']}</MenuButton>}
                onChange={({ open }) => !open && this.setState({show:false})}
            >

                {this.menuGeneration(menuItems, menuAnchor)}
            </Menu>
            {this.state.show && (
                <div
                    style={{
                        ...tooltipStyle,
                        left: this.state.pos.x,
                        top: this.state.pos.y
                    }}
                >
                    {this.state.tooltip}
                </div>
            )}
            </>

        );
    }

    menuGeneration(menuItems, menuAnchor) {

        if ( menuItems === undefined) {
            console.log('undefined LI/UL element',menuItems);
            return <></>;
        }

        if (!Array.isArray(menuItems)){
            console.log('non-array LI/UL element',menuItems);
            menuItems = [ menuItems ];
        }

        return (
            menuItems.map(({a, attributes, ul}) => {
                    if (ul !== undefined && ul.li !== undefined) {
                        return (
                            this.renderMenuItem(a, ul.li, true)
                        );
                    }

                    if (a === undefined) {
                        return (
                            <MenuDivider/>
                        )
                    }

                    return (
                        <MenuItem
                            key={menuAnchor.id}
                            value={a.attributes.id}
                            onClick={(id) => this.handleSelect(id)}
                            {...this.createTooltip(a.attributes.title)}
                        >
                            {a['#text']}
                        </MenuItem>)

                }
            )
        )
    }

    render () {

        const menuItemRendering = this.props.TMPMenuTestCategory.ul.li.map (({a,ul}) =>{
            // console.log('A-Title is',a.attributes.title,'UL-LI is', ul.li);
            return this.renderMenuItem(a, ul.li, false);
        });

        return (
            <div style={{display:'flex'}}>
                {menuItemRendering}
            </div>
        )
    }
}

export default TopMenuDropdown;
```

**Comment by szhsin** [comment]
You need to override the default style to move the arrow into the inner `div` and make it take up all the space of submenu item. https://codesandbox.io/s/react-menu-issue-130-tooltip-rywf6

It's more convenient to import `core.css` instead of `index.css` if you find yourself overriding a lot of the default styles.
https://szhsin.github.io/react-menu/style-guide

**Comment by VladParshin** [comment]
Thanks for the reply :) I'll look into in the coming days, but css shouldn't be hard to fix up. I'm still learning React, and I really appreciate the time you took to help me out, and hoping others who might run into similar things can now have something to go on.
