### ISSUE TITLE
Menu Item is not getting click when I integrate Dropdown under Aggrid React cell(Only in Safari browser)

### ISSUE THREAD

**Issue by dpk-mishra** [szhsin/react-menu#1303]
React/React-dom version: 18.2.0
React-Menu version: 4.1.0

## Describe the bug

This issue only comes in the Safari browser when the Menu is rendered under the Aggrid React Table cell. 

## To Reproduce

1. Use Aggrid React to disable a table layout.
2. Add Menu dropdown in any of the cells
3. Click on the Menu item to select the item.
4. Events are not getting triggered(Only in Safari)

## Expected behavior

Click event should get triggered when I select the menu Item

**Comment by szhsin** [comment]
Hey @dpk-mishra , I created an example and didn't see the issue in Safari: https://codesandbox.io/p/sandbox/react-menu-1303-6pndyl

**Comment by dpk-mishra** [comment]
> Hey @dpk-mishra , I created an example and didn't see the issue in Safari: https://codesandbox.io/p/sandbox/react-menu-1303-6pndyl

I missed passing portal props. It was working fine for every other browser except Safari. Thanks for the quick reply @szhsin
