### ISSUE TITLE
Menu Jiggle

### ISSUE THREAD

**Issue by danglez83** [szhsin/react-menu#1356]
React/React-dom version: 18.2.4
React-Menu version: 4.2.0

## Describe the bug
The menu shakes/jiggles rapidly when browser page size is smaller.

## To Reproduce

1. Make your browser height 1/3 - 1/2 your normal 
2. Set your zoom level below 100% (basically want to get the menu to have to render above the button and touch near top of window)
3. Expand menu
4. Menu shakes rapidly back and forth; the capture doesn't represent the speed of the jiggle, it's actually much faster.

## Code snippets/CodeSandbox examples/Screenshots

![jiggle](https://github.com/user-attachments/assets/215c52fc-bd26-4e49-90c2-417138fdb2d7)

**Comment by szhsin** [comment]
hey @danglez83, thanks for reporting the issue.

I took [this example](https://szhsin.github.io/react-menu#menu-overflow) and followed the steps but could not reproduce it.

Can you provide further details about your setup and environment? Did you set the [overflow](https://github.com/szhsin/react-menu/blob/441fc5b9f50795d3b620758796b60c7ae8c02266/types/index.d.ts#L244) prop on the menu?

https://github.com/user-attachments/assets/379437ae-6430-41d0-89f4-d380a4ffb601

**Comment by danglez83** [comment]
Here is my menu component setup (_DropdownMenuPortalTarget_ is rendered in the root):

![portal](https://github.com/user-attachments/assets/15870fd0-7a4a-415f-aa21-cdfff061004e)

...

The menu has the following props:

`direction = 'bottom',
align = 'end',
position = 'anchor',
viewScroll = 'close',
overflow = 'auto',
gap = 4,
shift = 0,`

The render looks like this:
![menu](https://github.com/user-attachments/assets/73fc60c5-4a87-47f7-a4ea-6ada4d4ffa35)
