### ISSUE TITLE
Menu remains aligned with "start" of anchor when anchor size changes and 'align="end"'

### ISSUE THREAD

**Issue by robmisasi** [szhsin/react-menu#1357]
React/React-dom version: 18.13.1
React-Menu version: 4.2.0

## Describe the bug
When the menu anchor resizes while the menu is opened, the menu shifts in response to changes in the position of the "start" of the anchor, even when explicitly aligned with another edge (e.g. "end").

## To Reproduce
See [CodeSandbox](https://codesandbox.io/p/sandbox/small-microservice-jw727y?file=%2Fsrc%2FApp.js%3A33%2C38).
This sandbox has a single menu button with a menu aligned with the "end" of the anchor. Clicking any of the menu items will change the label of the menu button thus changing it's size.

1. Open the Menu by clicking the button labeled "unclicked".
2. Click any of the menu items.
3. Observe the menu position shift in response to the new "start" position of the anchor while the "end" position remains the same.

## Expected behavior
The menu position should not change when the anchor element resizes if the position of the aligned edge also does not change.

## Code snippets/CodeSandbox examples/Screenshots
[CodeSandox](https://codesandbox.io/p/sandbox/small-microservice-jw727y?file=%2Fsrc%2FApp.js%3A33%2C38)

Before resize:
![Image before resize occurs](https://github.com/user-attachments/assets/44d6e001-c39d-400e-894c-f51f1b03e43b)

After resize:
![image after resize occurs](https://github.com/user-attachments/assets/bdcadfb2-71fe-46af-9f60-4b22529c6b37)

**Comment by szhsin** [comment]
hey @robmisasi , thanks for reporting the issue.

I can confirm we haven't re-computed and adjusted a menu's position in response to changes in anchor size. Will be fixing this issue in the next release.

**Comment by szhsin** [comment]
Fixed by [v4.2.1](https://github.com/szhsin/react-menu/releases/tag/v4.2.1)
