### ISSUE TITLE
Blocked aria-hidden

### ISSUE THREAD

**Issue by addlistener** [szhsin/react-menu#1365]
Seems like a new chrome version triggered some errors?

```
Blocked aria-hidden on a <li> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 
```
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/1ee1be46-17b4-483a-a60c-ded4e4a54501">

Chrome: 
Version 127.0.6533.89 (Official Build) (x86_64)

React/React-dom version: 
=> Found "react@18.2.0"

React-Menu version: 
=> Found "@szhsin/react-menu@4.1.0"

**Comment by szhsin** [comment]
Thanks for reporting the issue. Will be fixing it in the coming release.

**Comment by addlistener** [comment]
Wow it's fast!

Working now
