### ISSUE TITLE
preventDeafult on the onClick event of MenuItem

### ISSUE THREAD

**Issue by ajayvikas** [szhsin/react-menu#137]
I want to call event.preventDefault on the MenuItem.onClick event. However, the event object does not expose that. How can I accomplish it.

**Comment by szhsin** [comment]
Hi @ajayvikas , `onClick` is a custom event rather than the original DOM event, so `preventDefault()` is not available. 
Not sure what your use case is and there might be other ways to achieve it. Does calling `preventDefault()` of the `onMouseDown` work for you?

**Comment by szhsin** [comment]
If you are using `react-router-dom`, I think the page won't reload when switching route.
e.g.
```jsx
<MenuItem>
    <Link to={'/some-route'}>Item</Link>
</MenuItem>
```

If you use `<a>` tag directly, a workaround could be putting  `<a>` inside `MenuItem` and attach `onClick` on `<a>`.
e.g.
```jsx
<MenuItem>
    <a href="/some-route" onClick={(e)=> e.preventDefault()}>Item</a>
</MenuItem>
```
In either case, the `onClick` event on `MenuItem` still works as normal.

**Comment by ajayvikas** [comment]
Thanks @szhsin I used the second solution. I was worried this might not be the optimal way but since you have confirmed I am ok with it. Thanks for helping.

**Comment by szhsin** [comment]
Thanks for the feedback, this makes me realise overriding the `onClick` DOM event might not be a good design, as it makes the API inconsistent (all other DOM events are forwarded as it is) and can potentially prevent certain use cases like this one.

In the future, the `onClick` might be changed to a custom event such as `onSelect`. However, that's a breaking change and will only happen in a major release.
