### ISSUE TITLE
React Menu with NextUI's Modal component

### ISSUE THREAD

**Issue by rettimo** [szhsin/react-menu#1372]
I use `react-menu` to display context menu and submenu, as this functionality is not available in **NextUi** as the main ui library that I use in production. 
Everything worked fine, but at some point while using the portal I started getting incorrect behavior.
In the video below, you can see how after opening the menu and clicking on it, the modal window closes.

https://github.com/user-attachments/assets/dd7f962f-d3fe-41d9-94e1-7830dc3d509a

```typescript
import {
  Button,
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalHeader,
  Dropdown,
  DropdownTrigger,
  DropdownMenu,
  DropdownItem,
} from '@nextui-org/react'
import { ControlledMenu, MenuItem, useClick } from '@szhsin/react-menu'
import { useRef, useState } from 'react'
import '@szhsin/react-menu/dist/index.css'
import '@szhsin/react-menu/dist/transitions/zoom.css'

export const App = () => {
  const [isOpen, setIsOpen] = useState(false)
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const anchorProps = useClick(isMenuOpen, setIsMenuOpen)
  const ref = useRef(null)

  return (
    <div className="w-screen h-screen flex items-center justify-center">
      <Button
        onPress={() => {
          setIsOpen(true)
        }}
      >
        Open Modal
      </Button>
      <Modal isOpen={isOpen} onClose={() => setIsOpen(false)}>
        <ModalContent>
          <ModalHeader>Modal Header</ModalHeader>
          <ModalBody>
            This is the content of the modal
            <Button ref={ref} {...anchorProps}>
              Open menu
            </Button>
            <ControlledMenu
              anchorRef={ref}
              portal
              state={isMenuOpen ? 'open' : 'closed'}
              onClose={() => setIsMenuOpen(false)}
              direction="bottom"
              menuClassName="z-[10000]"
              align="center"
            >
              <MenuItem>New File</MenuItem>
              <MenuItem>Save</MenuItem>
              <MenuItem>Close</MenuItem>
              <MenuItem>Cut</MenuItem>
              <MenuItem>Copy</MenuItem>
              <MenuItem>Paste</MenuItem>
            </ControlledMenu>
            <Dropdown>
              <DropdownTrigger>
                <Button>Open Dropdown</Button>
              </DropdownTrigger>
              <DropdownMenu>
                <DropdownItem>New File</DropdownItem>
                <DropdownItem>Save</DropdownItem>
                <DropdownItem>Close</DropdownItem>
                <DropdownItem>Cut</DropdownItem>
                <DropdownItem>Copy</DropdownItem>
                <DropdownItem>Paste</DropdownItem>
              </DropdownMenu>
            </Dropdown>
          </ModalBody>
          <ModalFooter>
            <Button onClick={() => setIsOpen(false)}>Close</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </div>
  )
}
```

I'm not sure if this is a react-menu issue, but I can't seem to solve the issue with the portal and modal window. This applies not only to nextui, but to any modal window. Since, a click on react-menu is considered as a click outside for a modal window.

React/React-dom version: 18.3.1
React-Menu version: 4.2.2
@nextui-org/react virsion: 2.4.6

**Comment by szhsin** [comment]
If the modal closes due to a click outside of it, you may resolve it by stopping the `onClick` event from propagating up.
```diff
  <Menu
    menuButton={<MenuButton>Menu</MenuButton>}
+  onItemClick={(e) => e.syntheticEvent.stopPropagation()}
  >
    <MenuItem>Cut</MenuItem>
    <MenuItem>Copy</MenuItem>
    <MenuItem>Paste</MenuItem>
  </Menu>
```

**Comment by rettimo** [comment]
> If the modal closes due to a click outside of it, you may resolve it by stopping the `onClick` event from propagating up.
> 
> ```diff
>   <Menu
>     menuButton={<MenuButton>Menu</MenuButton>}
> +  onItemClick={(e) => e.syntheticEvent.stopPropagation()}
>   >
>     <MenuItem>Cut</MenuItem>
>     <MenuItem>Copy</MenuItem>
>     <MenuItem>Paste</MenuItem>
>   </Menu>
> ```

It doesn't help. The modal window still closes.

**Comment by szhsin** [comment]
With NextUI I did some tests, basically, the menu portal should be [targeted](https://github.com/szhsin/react-menu/blob/8273cd310bcb91b9eb6146da92a80c0cad1a532e/types/index.d.ts#L299) on the Modal itself. 

This is a working [sandbox example](https://codesandbox.io/p/sandbox/heuristic-jennings-32nlx7).

**Comment by rettimo** [comment]
Thank you very much, it really works!
