### ISSUE TITLE
Is it possible to render menus with multiple columns?

### ISSUE THREAD

**Issue by wanwari** [szhsin/react-menu#1374]
React/React-dom version: 16.14.0
React-Menu version: 4.0.2

Is it possible to render menus with multiple columns so the menu items are beside each other instead of all of them stacking one on top of the other?

![image](https://github.com/user-attachments/assets/bdf76469-0c38-4aa7-ae30-b2bb6e608276)

**Comment by szhsin** [comment]
The menu does not place restrictions on how the menu items should be laid out, so it's free to use whatever means to create your desired layout, e.g. using the CSS grid: [sandbox example](https://codesandbox.io/p/sandbox/react-menu-1374-nkzdp8)
