### ISSUE TITLE
How can I use this menu as a NAVBAR?

### ISSUE THREAD

**Issue by ccrowe-trimble** [szhsin/react-menu#1392]
I am wanting to use this as a NAV bar - do you have an example of how this could be achieved?

Chris

**Comment by szhsin** [comment]
Hi @ccrowe-trimble , navbar or menubar is not supported out of the box, but it's not hard to create one using the library.

Hope you find [this sandbox example](https://codesandbox.io/p/sandbox/react-menubar-1392-2gcc2d) helpful.

**Comment by ccrowe-trimble** [comment]
Thanks that really helps me.

Chris

**Comment by ccrowe-trimble** [comment]
Thanks that really helps me

Chris
