### ISSUE TITLE
boundingBoxRef is passed but got the null error (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by sook-cheng** [szhsin/react-menu#1431]
React/React-dom version: 18.3.1
React-Menu version: 4.2.2

## Describe the bug

I have a custom provider that wrapped my App component, and this react-menu package is used in the Header nav bar because I want to utilize the SubMenu component. But I got this error shown in the screenshot after added the custom provider in my project. 

![image](https://github.com/user-attachments/assets/7ca3f23b-ceed-41ef-86af-85af2f0c7dcf)

![image](https://github.com/user-attachments/assets/c7b6afc4-a6b2-4a1b-8b59-a164b3426044)

## To Reproduce

1. During the first load of the application, click on the MenuItem inside the SubMenu and navigate to another page.
2. Error pops up. Refresh the page with F5, error will be gone. 

## Suggestions

I suspect is because there is no null checking on the containerRef, before calling the getBoundingClientRect()

## Code snippets/CodeSandbox examples/Screenshots

Here is my code of how I implemented it.
![image](https://github.com/user-attachments/assets/6ec927cc-5aa9-437d-8d32-71feacbcab2e)

**Comment by szhsin** [comment]
hey @sook-cheng ,

I analyzed the code and don’t think the issue is likely to happen because of the order in which the menu and container are mounted. We can definitely add a check to skip the menu positioning if the ref is null, but that might hide a potential error. 
If you can share a CodeSandbox example to replicate the problem, that would really help!

**Comment by sook-cheng** [comment]
Hi @szhsin , thank you for your reply. I able to found another workaround which is add few secs delay during first time page load to ensure that component is already loaded and bind. So I able to implement the package in my solution without error now.

**Comment by szhsin** [comment]
**Update**:

In [v4.4.0](https://github.com/szhsin/react-menu/releases/tag/v4.4.0), we added a null check before positioning the menu to address an unrelated issue in React v19.10.0. However, that change also effectively prevents the error described in this issue from occurring.
