### ISSUE TITLE
Cannot extend MenuItem

### ISSUE THREAD

**Issue by tuan3w** [szhsin/react-menu#146]
Hi @szhsin,
Thanks for publish this library. I want to create `MyMenuItem` class to extend `MenuItem` class to provide some custom css. However, when I put `MyMenuItem` elements in the class inside `Menu` class, they don't show up. As a quick check in `MenuItem` source, it seems like I need to wrap `defineName` around `MyMenuItem`.  I think many people would get trouble because of this. Any way to make this work normally without using `defineName`?

https://github.com/szhsin/react-menu/blob/3b3e9c0c156319991b6981e09f8f539630d1a2f1/src/components/MenuItem.js#L20

Thanks.

**Comment by szhsin** [comment]
Hi @tuan3w , thanks for the feedback.
Not sure what styling system is used in your project.
If you're working with `styled-components`, it's straightforward to create custom component and it just works fine:
```jsx
const MyMenuItem = styled(MenuItem)`
  font-weight: bold;
`
```

If you're using pure css/scss solution, creating custom component (like `MyMenuItem`) is not required/recommended, you are able to override the default styles with your css, pls see the doc at: https://szhsin.github.io/react-menu/style-guide

In case you do want to create `MyMenuItem` to wrap and extend `MenuItem`, you might create an HOC of  `MenuItem`, there is [an example](https://codesandbox.io/s/react-menu-hoc-0bipn) and [doc](https://szhsin.github.io/react-menu/docs#utils-apply-hoc).

If you feel the HOC is overkill, you can do the following:
```jsx
const MyMenuItem = (props) => <MenuItem styles={{ fontWeight: 'bold' }} {...props} />
applyStatics(MenuItem)(MyMenuItem)
```
To make it work, two things are required:
- spread all `props` to `MenuItem`
- call `applyStatics` to let `Menu` know `MyMenuItem` is an `MenuItem`

Lastly, there are some other patterns that might be relevant to your use case at: https://github.com/szhsin/react-menu/issues/108
