### ISSUE TITLE
Has hidden dependency on prop-types

### ISSUE THREAD

**Issue by matthewjosephtaylor** [szhsin/react-menu#147]
Thanks for the great library! :)

New to react, so I don't have many libraries/deps installed

Had to do:

```
npm install --save prop-types
```

else I got:

```
Module not found: Error: Can't resolve 'prop-types' in ...
```

Suggest moving prop-types from devDependencies to normal dependencies.

**Comment by szhsin** [comment]
Hi @matthewjosephtaylor , thanks for reporting the issue.
`prop-types` is currently specified in the peerDependencies and you do get a warning of unmet peer dependency from `npm` when it's not installed.
I had a look at some other react libraries and saw many of them indeed put `prop-types` in the dependencies.
As people often ignore the npm warnings, it will be moved into dependencies in the next release.
