### ISSUE TITLE
Prevent Default

### ISSUE THREAD

**Issue by PercyTuncar** [szhsin/react-menu#154]
**Error:** Is there a way to prevent the page from reloading when browsing

**Comment by szhsin** [comment]
Hi @PercyTuncar , not sure what you mean page reloads when browsing
Here is an example about working with `React Router`, https://codesandbox.io/s/react-menu-react-router-example-dw4ku

**Comment by MaxiSantos** [comment]
@szhsin how can I make it work with nextjs ? For some reason MenuLink and Lin form next dosen-t work well. Im seeing a regular navigation where the page reloads completely.

**Comment by szhsin** [comment]
@MaxiSantos when MenuItem is used as a link, it has an internal `<a>` tag which cause page to reload. It is intended to be a url redirect, e.g. redirect to an external link.
You can call `e.syntheticEvent.preventDefault()` and use [history API](https://developer.mozilla.org/en-US/docs/Web/API/History)  to avoid a reload of page.
https://codesandbox.io/s/react-menu-react-router-example-dw4ku

**Comment by MaxiSantos** [comment]
> @MaxiSantos when MenuItem is used as a link, it has an internal `<a>` tag which cause page to reload. It is intended to be a url redirect, e.g. redirect to an external link.
> You can call `e.syntheticEvent.preventDefault()` and use [history API](https://developer.mozilla.org/en-US/docs/Web/API/History) to avoid a reload of page.
> https://codesandbox.io/s/react-menu-react-router-example-dw4ku

Thanks. I was hoping to use <Link> from nextjs but for now I'll go with your approach.
