### ISSUE TITLE
MenuList doesn't accept React.forwardRef'ed MenuItem

### ISSUE THREAD

**Issue by jhrinoa** [szhsin/react-menu#17]
Our application uses HOC with React.forwardRef call to add certain classNames and loggings. 
But, it looks like MenuList doesn't accept a React.forwardRef'ed MenuItem
https://github.com/szhsin/react-menu/blob/v1.2.2/src/components/MenuList.js#L109

Here is a super simplified codesandbox example to demonstrate the issue.
https://codesandbox.io/s/react-menu-forward-ref-example-lzfgu

I can do
`WrappedMenuItem.__name__ = 'MenuItem';`
But this looks too hacky.

Any suggestions?

**Comment by szhsin** [comment]
Hi @jhrinoa ,

Thanks for reporting the issue.

[v1.3.0](https://github.com/szhsin/react-menu/releases/tag/v1.3.0) released two utilities that help create HOC of react-menu components.
Please see the [document](https://szhsin.github.io/react-menu/docs#utils-apply-hoc) and [examples](https://codesandbox.io/s/react-menu-hoc-0bipn) for their usage.

As of v1.3.0, all **react-menu** components except the `MenuButton` don't apply React.forwardRef. This feature is in the roadmap and will be added in a future release.
