### ISSUE TITLE
How add style to rc-menu__submenu

### ISSUE THREAD

**Issue by tssobe** [szhsin/react-menu#178]
Hi
I would like to add class to rc-menu__submenu, is it possbile?

**Comment by szhsin** [comment]
Hi @tssobe , 
No, but you could add class to the submenu item (rc-menu__item) with `itemClassName`, or the submenu (rc-menu) with `className`.

**Comment by szhsin** [comment]
This use case became possible since v2.0.0, for example:

`<SubMenu label="Color" className="my-submenu">`
will render into DOM as:
`<li class="szh-menu__submenu my-submenu" role="presentation">`
