### ISSUE TITLE
Show Hotkeys?

### ISSUE THREAD

**Issue by JSchmidt63** [szhsin/react-menu#192]
Hello,
i want to check a way to show hotkeys in the menuitem (bound right, like in the picture?)
Thanks

![Hotkeys 2021-07-07 230152](https://user-images.githubusercontent.com/25293774/124828317-65fb4380-df77-11eb-960a-d50f44a04ccd.png)

**Comment by szhsin** [comment]
Hi @JSchmidt63 , 
Menu currently doesn't support hotkeys. 
If you need them, you can listen `keydown` event on `Menu` or the document and implement hotkey function in you code. To close the menu when hotkey is pressed, you will need to use the `ControlledMenu` by setting the `isOpen` prop to false.
