### ISSUE TITLE
ControlledMenu isOpen initially set to true

### ISSUE THREAD

**Issue by kaabij** [szhsin/react-menu#2]
I have a situation where I am expecting a ControlledMenu to be open by default. Simply hardcoding the isOpen prop to be true will result in a getBoundingClientRect error.

```
<button ref={buttonRef}>Menu</button>

<ControlledMenu
    anchorRef={buttonRef}
    isOpen={true}
>
...
```

Perhaps the button has yet to render and react-menu is attempting to determine the placement of the menu on the screen? I'm currently working around this by setting the isOpen to `false` and using a short timer to set open to `true`. But it is definitely not a good long-term solution.

[Code Sandbox](https://codesandbox.io/s/react-menu-material-uidefault-open-jydnk)

**Comment by szhsin** [comment]
Hi @kaabij ,
You are right, react-menu internally depends on a coupe of DOM elements to determine the position of menu related to its anchor element. However, this cannot be done before the anchor and menu are mounted into DOM. 
If you expect a menu to be open by default, you still need to have a `isOpen` state with initial value of `false`, and set it value to `true` after components have been mounted.
For example:
`const [isOpen, setOpen] = useState(false);
useEffect(() => {
    setOpen(true);
}, []);`

And if you are using class component:
`constructor() {
    this.state = { isOpen: false }
}

componentDidMount() {
    this.setState({ isOpen: true });
}`

**Comment by kaabij** [comment]
Thanks @szhsin. I'll do exactly that.
