### ISSUE TITLE
arrow and overflow doesn't work together

### ISSUE THREAD

**Issue by udah1** [szhsin/react-menu#202]
Hi, it seems that when enabling overflow, the arrow stops working.
is it possible to fix so both will work simultaneously?

**Comment by szhsin** [comment]
Hi @udah1 , 
css `overflow` on menu confines everything inside it, so the arrow div cannot be positioned outside. If you need arrow and overflow to work together, use a `MenuGroup` and apply overflow on the group. 
Here is an example: https://codesandbox.io/s/overflow-arrow-qkvjz

**Comment by udah1** [comment]
Thanks @szhsin. That looks great, but still not working for me.
I see that the overflow property is not working.
it seems the styles don't get dynamically changed for the menu and sub menus, while in examples they do.
(for example, max-height: 158px; overflow: auto; on the rc-menu__group item.

any ideas why it might happen?

![sample](https://user-images.githubusercontent.com/3235731/126670809-7340f3c5-9131-4ffa-a28e-b622f4d55bf3.png)
)

**Comment by udah1** [comment]
while in your sample:
![sample2](https://user-images.githubusercontent.com/3235731/126671034-ce82363b-98ff-4d39-ab6b-fd71d8b47e11.png)

**Comment by udah1** [comment]
Hi @szhsin, I have a problem with ADA on the example you gave. 
When opening the menu, I hear "menu with zero items".
This seems to be due to the group menu div which is coming between the "ul" and the "il's".

any resolution for that?

![image](https://user-images.githubusercontent.com/3235731/136789363-7c9a2fcb-a85a-43ce-8c10-be0ae2fa1add.png)

**Comment by szhsin** [comment]
Looks like the wrapping group has some impacts on screen reader. 
You might try to override the roles like this: 

```
    <Menu
      overflow="auto"
      position="anchor"
      role="presentation"
      arrow
      menuButton={<MenuButton>Open menu</MenuButton>}
    >
      <MenuGroup takeOverflow role="menu">
        {new Array(40).fill(0).map((_, i) => (
          <MenuItem key={i}>Item {i + 1}</MenuItem>
        ))}
      </MenuGroup>
    </Menu>
```
