### ISSUE TITLE
how one can keep submenu open by default ?

### ISSUE THREAD

**Issue by yasirhaleem** [szhsin/react-menu#216]
can we have state like below picture ? e.g keep the submenu open for first parent ?
![Screenshot 2021-08-06 at 1 07 22 AM](https://user-images.githubusercontent.com/989956/128499785-5ed2e967-31c4-4d73-b51c-f9c89b426a9d.png)

**Comment by yasirhaleem** [comment]
like when i click on open menu a list of parent and submenu for first parent should be in open state

**Comment by szhsin** [comment]
Hi @yasirhaleem , if I understand correctly, you would like the first submenu to be open by default (automatically) after parent menu is open.

`<SubMenu/>` is implemented as an uncontrolled component so you don't have a direct control of its open state.
For this kind of unusual case I recommend attaching a `ref` to submenu item and fire an `onClick` event explicitly after the parent menu opens. 

You can see an example at: https://codesandbox.io/s/react-menu-issue-216-fz88p
I created a wrapping `<div>` in `label` prop for attaching a `ref`.
In the next release, `ref` will be forwarded to the internal node so you can get rid of the `<div>`.

**Comment by yasirhaleem** [comment]
Hi @szhsin  Thanks a lot, this is what exactly i wanted.

if i have multiple submenu, onMouseOut i can fire the same function so when mouse is out of menu, first submenu will be open state again right ? seems like its not working

`onMouseOut={({ open }) => {
        if (open) {
          ref.current.dispatchEvent(
            new MouseEvent("mousedown", { bubbles: true })
          );
          ref.current.click();
        }
      }}`

and what else is being passed here `onMouseOut={({ open }) => {`

**Comment by szhsin** [comment]
`onMouseOut` is the native dom event, but in this case you can use `onMouseLeave` instead. Please see the updated example.
