### ISSUE TITLE
Clicking Checkboxes and Radio Menu items is closing the Menu.

### ISSUE THREAD

**Issue by aravindsurya77** [szhsin/react-menu#22]
I am trying to use checkbox menu items and MenuRadioGroup with **normal Menu** (not the ControlledMenu). Keyboard navigation and selection seems to be great. And when selected any menuItem with spaceBar, the item gets selected/unselected accordingly and the Menu will be still in **OPEN** state. But whereas, when I try to use EnterKey OR use a mouse click the menuItem gets selected/unselected but in this case, the Menu is **closing**. Is there a way to let the Menu (not ControlledMenu) stay open when the user hits Enter/mouse click on a checkboxMenuItem or RadioGroupMenuItem.

**Comment by szhsin** [comment]
Hi @aravindsurya77 ,

Thanks for your feedback.
Will release an update that allows to control when menu is closed. Please note the current behaviour is the [W3C recommendation](https://www.w3.org/TR/wai-aria-practices/#menu).

**Comment by szhsin** [comment]
Feature released in [v1.5.0](https://github.com/szhsin/react-menu/releases/tag/v1.5.0). Here is [an example](https://codesandbox.io/s/react-menu-keepopen-dzscw) demonstrating multiple use cases.

**Comment by aravindsurya77** [comment]
Thank you so much @szhsin!
