### ISSUE TITLE
SubMenu onClick Event

### ISSUE THREAD

**Issue by ManiruzzamanAkash** [szhsin/react-menu#228]
Hello,
It's `onClick` event working with `<MenuItem />` but not in `<SubMenu />`

In `SubMenu` it has `onChange` props. But in my case, I need to add an onClick event when `Submenu` is clicked. Something like this - 
```jsx
<SubMenu label="Category 1" onClick={() => console.log('clicked')}> {/* There is no onClick props actually */}
    <MenuItem />
</SubMenu>
```
I've tried also by adding a parent div, but not working. Then menu is not coming.
```jsx
<div onClick={() => console.log('clicked')}>
     <SubMenu label="Category 1">
            <MenuItem />
    </SubMenu>
<div>
```

Is there any possibility to achieve this ?

**Comment by szhsin** [comment]
Hi @ManiruzzamanAkash ,
`onClick` of `<SubMenu/>` fires when the submenu itself is clicked;
If you want to listen `onClick` event on submenu item, currently the solution is to add a wrapping `<div>` on `label` prop and attach `onClick` on the `<div>`.
e.g.: https://codesandbox.io/s/react-menu-issue-228-x5buj
Please make sure click the text 'Open' in submenu item when testing, unless you override styles and remove the padding around the item.

In the next coming release, there will be an additional prop which allows to add event handlers on the `label` directly.

**Comment by ManiruzzamanAkash** [comment]
Great. `onClick` event works perfectly on `<SubMenu />` using this approach. Thanks.
