### ISSUE TITLE
SubMenu arrows get distorted

### ISSUE THREAD

**Issue by tssobe** [szhsin/react-menu#233]
Hi
I am using the SubMenu as follow:
<img width="349" alt="arrows2" src="https://user-images.githubusercontent.com/8546137/129887956-f726a73c-c964-4837-a7aa-78b6d73e9d06.PNG">

for some reason, is random times, the submenu arrow is being distorted

![arrow](https://user-images.githubusercontent.com/8546137/129887667-c4a261e1-85e3-4a5e-8139-1644fdc22b38.jpg)

Any idea why it gets distorted?

**Comment by szhsin** [comment]
Hi @tssobe , it's hard to tell what problem might be from the screenshots. Can you post a minimal example showing the issue?

**Comment by tssobe** [comment]
Hi @szhsin , the issues that the arrows of the submenu become distorted as you can see in the screenshot.
Without the distortion is should look:
<img width="118" alt="arrows3" src="https://user-images.githubusercontent.com/8546137/129919145-b4ed3324-daa7-4cd5-a1a0-c52bb2c7e6e8.PNG">

**Comment by szhsin** [comment]
It looks like a styling issue. If you are using the arrow which comes with the default style, it's an `::after` pseudo-element that might be overridden by your global style sheets under some conditions.
Try to create the arrow with a div in the label `prop` to see if the problem resolves.
