### ISSUE TITLE
Menu isn't being anchored to the anchor element

### ISSUE THREAD

**Issue by mrodrigues95** [szhsin/react-menu#26]
**What happened**

I cannot get the Menu top level component to properly anchor and position to the trigger.

**Problem description**

I grabbed a piece of sample code from the docs to try and experiment with the library. If you take a look at the code below, you will see that I'm trying to render the `Menu` inside a `portal` and have it positioned to the right of the `MenuButton`.

After running this code in my application, you can see that the `Menu` is being rendered to the bottom of the page instead of being anchored to the right of the trigger element. I'm not sure if I am incorrectly using the library or if this is a bug?

I've tried removing the `portal` prop and tinkering with the `position` and `offset` properties but have had no success.

**Relevant code**

```
const TestMenu = () => {
  return (
    <Menu
      menuButton={<MenuButton>Open menu</MenuButton>}
      align="center"
      direction="right"
      portal
    >
      <MenuItem>New File</MenuItem>
      <MenuItem>Save</MenuItem>
      <MenuItem>Close Window</MenuItem>
    </Menu>
  );
};
```
![image](https://user-images.githubusercontent.com/38141653/104127308-6d76c280-532f-11eb-89da-75c922b422b2.png)

**Comment by szhsin** [comment]
Hi @mrodrigues95 ,

Thanks for reporting the issue.
It looks like you didn't import the default style with `import '@szhsin/react-menu/dist/index.css'`.
If you've done it but still have the issue, could you give more details about your code or ideally reproduce the issue with a codesandbox example?

**Comment by mrodrigues95** [comment]
Hi @szhsin,

Looks like I was missing the style sheet indeed, works now.

Thanks!
