### ISSUE TITLE
react-testing-library example?

### ISSUE THREAD

**Issue by kaabij** [szhsin/react-menu#3]
I'm currently adding some tests using react-testing-library, but I am having a difficulty with verifying that the menu has closed. In particular, it does not appear that the class `rc-menu--open` is removed after clicking the button a second time. I have tried setting the prop `keepMounted={false}` and updated my test logic, but that also does not appear to work.

This may not be an issue with react-menu itself, but the way I am testing it with react-testing-library.

```javascript
const PredefinedMenu = () => {
  return (
    <Menu
      menuButton={<button>Test Menu</button>}
      keepMounted={false}
      animation={false}
    >
      <MenuItem value="item1">Item 1</MenuItem>
      <MenuItem value="item2">Item 2</MenuItem>
      <MenuItem value="item3">Item 3</MenuItem>
    </Menu>
  )
}

test('react-menu', async () => {
  const {container} = render(<PredefinedMenu />)
  const menuButton = container.querySelector('button')
  expect(container).toBeInTheDocument()

  // First render will not render the list element and only render the button
  expect(container.querySelector('ul')).toBe(null)
  expect(menuButton).toHaveTextContent('Test Menu')

  // Upon clicking the button, the list element will be rendered and displayed
  fireEvent.click(menuButton)
  expect(container.querySelector('ul')).not.toBe(null)
  expect(container.querySelector('ul')).toHaveClass('rc-menu--open')

  // Upon clicking the button again, the menu should close and be removed from DOM
  fireEvent.click(menuButton)
  await waitForElementToBeRemoved(container.querySelector('ul'))
})
```
[Code Sandbox](https://codesandbox.io/s/react-menu-test-vg9nk?file=/src/__tests__/react-menu.js:175-1267)

**Comment by szhsin** [comment]
Hi @kaabij ,
Clicking the menu button only causes menu to open.
Closing a menu relies on the onBlur event. As a result, simply focus something outside the menu will cause it close.

I pushed an example that demonstrates the behaviour: https://github.com/szhsin/react-menu/blob/e50fc6908b6040cfc59fd00ce825cfc199f1f5c4/src/components/__tests__/Menu.test.js#L89

**Comment by kaabij** [comment]
Thanks for the prompt response @szhsin!

I also noticed that if the test does not wait for focus to land on the menu itself, the test will fail. Anyways, appreciate all the tests you have added in e50fc6908b6040cfc59fd00ce825cfc199f1f5c4.
