### ISSUE TITLE
Disable submenu on hover 

### ISSUE THREAD

**Issue by jefersonjuliani** [szhsin/react-menu#312]
Hello, 

I'm using a button to open the submenu, 
I don't wanted the submenu open on hover,
but the hover style don't work if a use the  disabled={true}...
can you help me ?

` <Component
        {...props}
        className="subMenuCSS"
        instanceRef={subMenuRef}
        disabled={true}
        label={
          <InnerMenuItem
            onOptionClick={() => {
              subMenuRef.current.openMenu();
            }}
            {...props}
          />
        }
        itemProps={itemProps}
      />`

**Comment by szhsin** [comment]
@jefersonjuliani
With [v2.3.0](https://github.com/szhsin/react-menu/releases/tag/v2.3.0) there is a new prop `openTrigger` on `SubMenu` component. Simply setting it to "clickOnly" or "none" will disable open on hover.
``` jsx
<Menu menuButton={<MenuButton>Open menu</MenuButton>}>
  <SubMenu label="Edit" openTrigger="clickOnly">
    <MenuItem>Cut</MenuItem>
    <MenuItem>Copy</MenuItem>
    <MenuItem>Paste</MenuItem>
  </SubMenu>
  <MenuItem>Print...</MenuItem>
</Menu>
```
