### ISSUE TITLE
Programatically set focus of first menu item

### ISSUE THREAD

**Issue by hazzo** [szhsin/react-menu#331]
Hi, it's possible to programatically set focus in the first item element? 

I know that there is prop for controlled menu that let's you do this but on menu open (`menuItemFocus`). But if a set `captureFocus = false` I would like to:
1- open menu
2- make some actions
3- set focus to first item.

Would this be possible?

Thanks!!!

**Comment by szhsin** [comment]
Hi @hazzo 
Not sure I understand the use case correctly but please see this as an example: https://codesandbox.io/s/react-menu-issue-331-xy4y5

**Comment by hazzo** [comment]
@szhsin thanks! thats right what I wanted! I'll test with my implementation of a keyboard event but it should do the trick. Thanks again.
