### ISSUE TITLE
ControlledMenu toggle on hover one at a time

### ISSUE THREAD

**Issue by alive8794** [szhsin/react-menu#342]
Hi,
I have multiple ControlledMenu which should toggle on hover one at a time, however they ar both getting toggled together at the same time. 

I couldn't find any example of multiple hover Controlled Menu

Please help me out as I am in urgent need of implementing the menu

**Comment by szhsin** [comment]
Hi @alive8794 
I guess you used a single shared state for multiple `ControlledMenu`.
Instead, you need to provide separate state to each menu, which means each menu will need an individual  `useState` or `useMenuState` call.
I can provide an example later if you still need help.

**Comment by alive8794** [comment]
Hi @szhsin,

I tried doing that, defining individual useState or useMenuState call, however, I keep getting the error that toggleMenu is already defined.

I am new to react so I am probably missing something.

I would really appreciate if you can help me with the example.

**Comment by alive8794** [comment]
Hey, 
I tried and I was able to achieve this with the useState call but would like to still know the way to use multiple useMenuState.

If you can still post the example for that it would be really helpful :)

**Comment by szhsin** [comment]
Here is an example using two menus: https://codesandbox.io/s/react-menu-issue-342-r6ln1
You could extract a common component or hook to implement it as well.
