### ISSUE TITLE
stopPropagation on MenuItem doesn't work as expected

### ISSUE THREAD

**Issue by moroshko** [szhsin/react-menu#389]
Based on [this example](https://szhsin.github.io/react-menu/#event-handling), I'm trying to set `stopPropagation` on the event object to `true`. However, it doesn't seem to work.

Repro:
1. [CodeSandbox](https://codesandbox.io/s/react-menu-starter-forked-dxmrl)
2. Click "Open menu"
3. Click "Delete"

**Observed behavior:** "click proparated to the parent div" appears in the console

**Expected behavior:** it shouldn't appear

What am I missing here?

**Comment by szhsin** [comment]
Hi @moroshko 
The boolean `stopPropagation` prevents `onItemClick` on root menu component from firing.
`onItemClick` is a custom event on `Menu` component.

If you want to stop the native `onClick`  event from propagating to ancestor elements, you may call `e.syntheticEvent.stopPropagation()` method.

Here is an example: https://codesandbox.io/s/react-menu-issue-389-fvyf5

**Comment by moroshko** [comment]
Awesome, thanks a lot @szhsin ❤️

**Comment by moroshko** [comment]
@szhsin How would you stop propagation on disabled items?

[CodeSandbox](https://codesandbox.io/s/react-menu-starter-forked-jxzsd?file=/src/App.js)

**Comment by szhsin** [comment]
@moroshko sorry for the late reply. 
It looks like the native html tags (`<button/>` for example) automatically call `stopPropagation` and `preventDefault` when disabled. Therefore this is indeed a bug.

**Comment by moroshko** [comment]
@szhsin Any workarounds for now, or an idea when this might be fixed?

**Comment by szhsin** [comment]
It should be a quick fix, I will do it today.

**Comment by szhsin** [comment]
Issue fixed in [v2.3.4](https://github.com/szhsin/react-menu/releases/tag/v2.3.4).

**Comment by moroshko** [comment]
Thanks a lot @szhsin !!
