### ISSUE TITLE
Add Href Link to MenuButton

### ISSUE THREAD

**Issue by husleuujii** [szhsin/react-menu#4]
How do I to add href to menubutton? is this possible? Its only works in menuItem any solution bro?

**Comment by szhsin** [comment]
Hi @husleuujii ,

You can provide an `<a>` tag to the `menuButton` prop of `Menu`, e.g.:
```jsx
        <Menu menuButton={<a href="your_url">Open</a>}>
            <MenuItem>New</MenuItem>
            <MenuItem>Save</MenuItem>
        </Menu>
```
However, I think this use case doesn't very make sense. If you click the link to open menu, the url of link is activated at the same time.

I guess what you might want to implement is a use case as below:
When the link is hovered, open the menu.
When the link is clicked, go to the url of the link.

It can be implemented with the `ControlledMenu`. 
You will have totally control of: 
1) how menu is open and closed (with mouse enter and leave events)
2) what controls the menu's open and close (an `<a>` tag with `href`)

**Comment by husleuujii** [comment]
Can you give me example ? I tried with mapping data. But doesnt really work.. 
`{categories.map((category) => (
        <>
          <button
            ref={ref}
            className="btn btn-dark"
            onMouseEnter={() => setOpen(true)}
          >
            {category.name}
          </button>
          <ControlledMenu
            anchorRef={ref}
            isOpen={isOpen}
            onMouseLeave={() => setOpen(false)}
            onClose={() => setOpen(false)}
          >
            <MenuItem>New File</MenuItem>
            <MenuItem>Save</MenuItem>
            <MenuItem>Close Window</MenuItem>
          </ControlledMenu>
        </>
      ))}`
I added ```
const [isOpen, setOpen] = useState(false);
  const ref = useRef(null);
```

**Comment by husleuujii** [comment]
[https://ibb.co/QMrW7r5](url) here is picture,

**Comment by szhsin** [comment]
Use MouseEnter event to open menu:

```jsx
    const { openMenu, closeMenu, toggleMenu,
        ...menuProps } = useMenuState();
    const ref = useRef(null);

    return (
        <>
            <a ref={ref} href="your_url" 
                onMouseEnter={() => openMenu()}>
                Open
            </a>

            <ControlledMenu {...menuProps} anchorRef={ref} animation={false}
                onClose={() => closeMenu()}>
                <MenuItem>New</MenuItem>
                <MenuItem>Save</MenuItem>
            </ControlledMenu>
        </>
    );
```

**Comment by husleuujii** [comment]
man ur da best <3 love you

**Comment by husleuujii** [comment]
im totally done but does  <SubMenu> support href? I did like  <SubMenu href={`/products?category_id=${subCategory.id}`} label={subCategory.name}> , Im doing nextjs project but dont know how to use <Link> on menu`s but im doing manually like giving href.

**Comment by szhsin** [comment]
Currently you can add `href` to a `<MenuItem/>` but not `<SubMenu/>`.

**Comment by husleuujii** [comment]
There is no way?..

**Comment by szhsin** [comment]
Well, technically it can be done, but the accessibility will be broken. 
If there is a `href` on the `<SubMenu/>`, and the submenu is activated with keyboard (e.g. with 'Enter' key), then only one action can be taken between opening the submenu and going to the url link.

**Comment by husleuujii** [comment]
can u make it  possible to adding href to submenu? i think there might be possible.

**Comment by szhsin** [comment]
Starting from [v1.0.2](https://github.com/szhsin/react-menu/releases/tag/v1.0.2), you can put a link in a submenu item with the `label` prop. The link will be activated when clicked, however, keyboard events will still open submenu.

``` jsx
<Menu menuButton={<MenuButton>Open</MenuButton>}>
    <MenuItem>New</MenuItem>
    <SubMenu label={<a href="your_url">Link</a>}>
        <MenuItem>One</MenuItem>
        <MenuItem>Two</MenuItem>
    </SubMenu>
    <MenuItem>Save</MenuItem>
</Menu>
```
If you are working with React-Router, you can use the `<Link/>` component instead of `<a>`.
You might need to change the style of link to match you design.
