### ISSUE TITLE
It is capturing the mouse position and selecting the item at the mouse position

### ISSUE THREAD

**Issue by galexandrade** [szhsin/react-menu#400]
We would like to initialize the menu with the first item selected. To achieve this we are using the `menuItemFocus` prop:
```
menuItemFocus={{
    position: 'first',
}}
```

The issue happens when the mouse cursor is positioned in a place where it will trigger the `onMouseEnter` and will select the item that is at the cursor position making the first item not being selected by default.

![menu-cursor](https://user-images.githubusercontent.com/24475665/150433432-98947e51-18ff-414c-8d17-10bd244eb709.gif)

**Comment by galexandrade** [comment]
I was playing around with a possible solution and I created this PR: https://github.com/szhsin/react-menu/pull/401.
I would appreciate reviews.

**Comment by logan-markewich** [comment]
This is a very annoying issue. Would love to see this get fixed!

**Comment by szhsin** [comment]
Fixed and released in [v2.3.3](https://github.com/szhsin/react-menu/releases/tag/v2.3.3).

**Comment by galexandrade** [comment]
> Fixed and released in [v2.3.3](https://github.com/szhsin/react-menu/releases/tag/v2.3.3).

Thank you @szhsin
