### ISSUE TITLE
problem with direction for sub menu

### ISSUE THREAD

**Issue by soheilhassanjani** [szhsin/react-menu#428]
hi , when show submenu , at first time , check submenu can show in viewport , if not , direction is reverse . if have many submenu , and all directions is end , for submenu can't show , reverse direction and for normal submenu , direction is end . now i need to if reverse direction in each submenu ( first , second ,... ) , from now on submenu direction that reverse . you have solution for this problem ?

**Comment by szhsin** [comment]
I don't quite understand your case. You may try to set the `direction` prop to "left".
```js
<SubMenu direction="left">
```
If that's not what you want, please post a screenshot or CodeSandbox example.

**Comment by soheilhassanjani** [comment]
The problem is that after it reaches an end the opening direction changes, What I want is for it to continue in the new direction while opening submenu of the original submenu (sub-submenu). First it opens to left and then right and left again. 
It will be like Left -> Right -> Left -> Right ... .I want them to be like Left -> Right -> Right until it reaches the other end.

**Comment by szhsin** [comment]
I guess I've understood the use case. Just had a check of the native menu on macOS and it works in this way.
The library doesn't support it at the moment but this could be a valid feature.
I will implement it in a future release.

**Comment by soheilhassanjani** [comment]
Thank u 🙏

**Comment by szhsin** [comment]
Released in [v3.0.2](https://github.com/szhsin/react-menu/releases/tag/v3.0.2)
