### ISSUE TITLE
How to Track Display state of SubMenu Content

### ISSUE THREAD

**Issue by Dagnarrus** [szhsin/react-menu#429]
Hi, I am wrapping a submenu to display a grid of items for the menu. The menu is a bit unwieldy leaving all of the items in a line. So I changed the display of the list to flex and wrap the items. The problem I am running into is that the SubMenu does not close if I change the display setting for the unordered list that gets rendered. 
I am seeing the class names change indicating the state is updating, but am not seeing the wrapped component update. If I want to be aware of it's state change, should I wrap the MenuList and provide that as the only child to the SubMenu, or is there some other way in which I could watch this value?

```
const MyMenu = () => {
    applyStatics(SubMenu)(ColorMenu);
    applyStatics(SubMenu)(AnotherMenu);

    return (
        <Menu menuButton={<MenuButton>{ButtonContent}</MenuButton>}>
            <AnotherMenu />
            <ColorMenu />
            <MenuDivider />
            <MenuItem>Last Item</MenuItem>
        </Menu>
    );
}

const AnotherMenu = (props) => {
    return (
        <SubMenu
            {...props}
            label='Another Menu'
            >
            <MenuItem>
                Item 1
            </MenuItem>
            <MenuItem>
                Item 2
            </MenuItem>
        </SubMenu>
    );
}

const ColorMenu = (props) => {

    const colors = useMemo(() => GetColorsFromSomewhere(), []);

    applyStatics(MenuItem)(ColorBlock);

    const ColorGrid = styled(SubMenu, { 
        '& ul': {
            display: 'flex',
            flexWrap: 'wrap',
            maxHeight: '425px'
        },
         /* Additional styling here */ 
    });

    return (
        <ColorGrid
            {...props}
            label='My Color'
            >
            {colors.map(color => (
                <ColorBlock
                    key={color.name}
                    color={color}
                    />
                )
            )}
        </ColorGrid>
    );
}

const ColorBlock = ({ color, ...props }) => {
    
    const Block = styled(MenuItem, { /* Styling here */ });

    return (
        <Block {...props}>
            // color block content here
        </Block>
    );
}
```

Thank You

**Comment by TeturactsWill** [comment]
To update a bit, I imported and tried wrapping the MenuList component. That caused issues with some internal code calculating and/or setting position on the items in the sub menu. So I undid those changes.

I ended up going with a work around by changing the style that sets display flex to `& ul.szh-menu--state-open': { display: 'flex' }`. Which works, but seems to break some of the animations. 

Is there an event that gets fired during any of these state changes? perhaps that would be a cleaner approach for managing the display of custom/wrapped components within the menu.

Thanks

**Comment by szhsin** [comment]
Hi @TeturactsWill ,
Menu has four states when transition is enabled: 
- 'opening'
- 'open'
- 'closing'
- 'closed'

It is visible on screen unless state is 'closed'.

There is a css rule in default stylesheets to hide menu when closed.
```css
.szh-menu--state-closed {
  display: none;
}
```
If you override `display` of a menu to 'flex' in CSS-in-JSS with selector `.szh-menu` or `ul`, the `display` of every menu state will be overridden as the default stylesheets have lower css specificity.
So the simplest solution is to explicitly add the above css rule in your CSS-in-JSS again.
https://codesandbox.io/s/react-menu-issue-429-gz8r9m
I use `style-utils` which comes with the package in the example. It would be the same if you write out the css selector directly.

Of course, you might also apply 'flex' to every menu state except the 'closed' one, but it has more code and won't be resilient when new menu states are added in the future.
```css
.szh-menu--state-opening,
.szh-menu--state-open,
.szh-menu--state-closing {
   display: flex;
   flex-wrap: wrap;
}
```

**Comment by TeturactsWill** [comment]
Thank you for the info. I've gone ahead and moved the apply statics outside of the component functions per your recommendation. 

For the display, the style is only being applied on that wrapped SubMenu component, so I would not expect the other elements to be affected. I went ahead and updated it as well. to `'& ul:not(.szh-menu--state-closed)'`. This seems to have fixed what I broke with the transitions. 

A bit off topic. But I was slightly confused going through some of the examples. Is applyHOC intended only for use within redux? I wasn't entirely sure if I should only be using applyStatics, or attempting to return a component run through that other function.

**Comment by szhsin** [comment]
Good point, `'& ul:not(.szh-menu--state-closed)'` works as well. I updated the example. Please be aware that `ul` is an implementation detail and not part of the library API. In this case I would be better to use `'.szh-menu:not(.szh-menu--state-closed)'`.

`applyHOC` is used to create higher-order components over `MenuItem` or `SubMenu`, not necessarily with redux. `applyStatics` is used to create new components wrapping `MenuItem`, `SubMenu`, just like your code example. 

The purpose of these two functions is to support keyboard navigation through menu items when users create their own React components over `MenuItem`. I understand they're causing confusion for many users, so I'm working on a reimplementation of keyboard navigation mechanism and, once finished, these two functions will be removed.
