### ISSUE TITLE
How can 'react-menu' escape a scrollable container

### ISSUE THREAD

**Issue by Crazy-Ivan** [szhsin/react-menu#430]
HI! I have a quite unusual use case. I use the react-menu inside a narrow scrollable container. Because the container has an overflow set the menu becomes unusable (due to container narrow size). Is there any easy way to make react-menu render outside this container to be able to escape from the overflow: scroll? Something like render target?

**Comment by szhsin** [comment]
Hi @Crazy-Ivan , `Menu` has a `portal` prop which is designed for this case. Setting it `true` will allow menu to render directly under `document.body`.

**Comment by Crazy-Ivan** [comment]
Hello @szhsin. Thank you! This is exactly what I was looking for! Great library by the way! 

Just one thing to consider. Adding the possibility to pass a reference to the HTML where a menu will be rendered would help in case of dynamic theming based on CSS variables attached bellow `document.body`.
