### ISSUE TITLE
open menu on hover

### ISSUE THREAD

**Issue by mdnafeed** [szhsin/react-menu#451]
**how can i open menu on mouse hover** ??

example: when user move to menu i don't want to click mouse on menu. i need to open menu on **Hover**

**Comment by szhsin** [comment]
Hi @mdnafeed , 
you can use `ControlledMenu` component to manage what triggers menu to open, here is a very basic example: https://szhsin.github.io/react-menu#managing-state 

If you want to enable opening and closing transitions and make them smooth, a timer can be used to bridge the mouse enter and leave events, https://codesandbox.io/s/react-menu-hover-open-i7isjv

**Comment by mdnafeed** [comment]
Thanks You @szhsin
