### ISSUE TITLE
Reacting on direction change event

### ISSUE THREAD

**Issue by domipieg** [szhsin/react-menu#489]
React/React-dom version: 16.8.5
React-Menu version: 2.3.4

Hi, I am trying to get information if displayed menu is having top or bottom direction. Also I need to react on the direction change (When I scroll I need to know when menu moved from bottom to top direction). Is it possible on 2.3.4 version?

**Comment by szhsin** [comment]
Hi @domipieg , there isn't an event that notifies change in menu direction. If you want to know menu direction for styling purpose, you could use the `menuClassName` prop as a function which receives menu direction in its parameters. 
If you want to know menu direction for other reasons, can you please provide more details about the use case?

**Comment by domipieg** [comment]
That solves my problem. Thank you :)
