### ISSUE TITLE
how to hover main menu for open submenu

### ISSUE THREAD

**Issue by shipcake** [szhsin/react-menu#49]
Hi. main menu will open when user clicked context menu. I want to hover context menu and context menu will active
Thank

**Comment by szhsin** [comment]
Hi @shipcake, thanks for your feedback. 
I don't quite understand what's the issue here. Can you describe it more clearly or with an example?

**Comment by szhsin** [comment]
Close issue for not enough information.

**Comment by singhaishwarya** [comment]
@shipcake  wants to open the submenu on hovering instead of clicking.

**Comment by szhsin** [comment]
> @shipcake wants to open the submenu on hovering instead of clicking.

This is already the default behaviour.

**Comment by singhaishwarya** [comment]
no this isn't the case....you need to click on the main menu then submenus open and then hover over the submenu then the subsequent option opens...

**Comment by szhsin** [comment]
> no this isn't the case....you need to click on the main menu then submenus open and then hover over the submenu then the subsequent option opens...

I still don't understand, do you mean "click on the main menu then submenus open" by itself?

**Comment by srch07** [comment]
> > no this isn't the case....you need to click on the main menu then submenus open and then hover over the submenu then the subsequent option opens...
> 
> I still don't understand, do you mean "click on the main menu then submenus open" by itself?

I have similar requirement. I want to use this menu in a way, that I don't need to click on menuButton to open the menu. 
How to auto open it on hover of top element.
