### ISSUE TITLE
Currently opened submenu should stay open while mouse moves towards it

### ISSUE THREAD

**Issue by dutzi** [szhsin/react-menu#50]
Most menus nowadays implement some logic that keeps the currently opened submenu open while the mouse moves towards it, even if that mouse hovers over another menu item (in the parent's list) on its way to the currently opened submenu.

This can be achieved by setting a timeout for the submenu's hide callback, within that timeout if the mouse hovers over a parent's list menu item, the submenu will be kept open.

Frustrating: https://i.imgur.com/iTOORe3.gifv

Not frustrating: https://i.imgur.com/e5eB4bx.gifv

**Comment by szhsin** [comment]
Hi @dutzi , thanks for your feedback. 
Will try to improve this interaction of submenu and release a fix in the next version.

**Comment by dutzi** [comment]
Thank you!

Here's a pretty in-depth article about the problem and several possible ways to approach it. 

https://css-tricks.com/dropdown-menus-with-more-forgiving-mouse-movement-paths/

**Comment by szhsin** [comment]
The UX improvement was released in [v1.6.1](https://github.com/szhsin/react-menu/releases/tag/v1.6.1) @dutzi

**Comment by dutzi** [comment]
That's great! Thanks for the update :)
