### ISSUE TITLE
How to style MenuButton (with style component)

### ISSUE THREAD

**Issue by SpiderSeb** [szhsin/react-menu#514]
React-Menu version:3.0.1

Is it possible to style MenuButton with style component ?

I tried in many ways, but never fully satisfying

`const StyledMenu = styled(Menu)
    ...
    ${menuButtonSelector.name} {
        background: blue;
    }`

This way doesnt work at all as the menu button is not inside the menu entry in the dom

`const StyledMenuButton = styled(MenuButton)
    background: yellow;
`
This way work, but the button in the dom does not have the aria-expanded property anymore.
Is it a bug ? Or

**Comment by szhsin** [comment]
Hi @SpiderSeb , the second way is correct and works, please check out this example https://codesandbox.io/s/react-menu-styled-components-forked-uink82
The `aria` attributes are preserved.

**Comment by SpiderSeb** [comment]
thanks for the sandbox. 👍🏼 
Very strange, i'll try to find why it doesnt work well with my config 🔍

**Comment by SpiderSeb** [comment]
When i copy paste your sandbox in my project, i get the problem.
The main difference is that i use @emotion not styled component

**Comment by szhsin** [comment]
`@emotion/styled` doesn't copy static properties from the source component when creating styled wrapper component, whereas `styled-components` does.

One solution is to copy statics using the [`hoist-non-react-statics` npm package](https://www.npmjs.com/package/hoist-non-react-statics
)
Please see the sandbox example https://codesandbox.io/s/react-menu-514-emotion-styled-forked-15ingn?file=/src/App.js:1427-1549

If you don't want to introduce an extra npm package, an alternative solution is to use functional form of the `menuButton` prop and set `aria-expanded` explicitly:
```jsx
<Menu
  menuButton={({ open }) => (
    <StyledMenuButton aria-expanded={open}>Open menu</StyledMenuButton>
  )}
>
```

**Comment by SpiderSeb** [comment]
Wow, it works perfect, thank you for your really quick answer.

Really impressive, you managed all edge cases, Well done !
