### ISSUE TITLE
Is it safe to use ref.current as useCallback's dependency?

### ISSUE THREAD

**Issue by xushicheng** [szhsin/react-menu#529]
Thanks for this nice project, I appreciate it!

Just curious, is it safe to use ref.current as useCallback's dependency???

eg:
https://github.com/szhsin/react-menu/blob/82a4bd94494ee4d5729cbc5527446250f0f27579/src/hooks/useItems.js#L27
https://github.com/szhsin/react-menu/blob/82a4bd94494ee4d5729cbc5527446250f0f27579/src/hooks/useItems.js#L99

I remember that ref.current isn't ok as the useEffect's deps, but what about useCallback???

And I can find some proof:
https://medium.com/welldone-software/usecallback-might-be-what-you-meant-by-useref-useeffect-773bc0278ae
https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom

Have a nice day! I love your project!

**Comment by szhsin** [comment]
Hi @xushicheng , thanks for your compliment to the project. I'm glad to hear you love it.

The ref dependency of `useCallback` is safe in this case. Notice that `ref.current` is never re-assigned after initial render. I use this pattern to merely simulate the instance variables in a class component (things that should be persisted but not belong to React state). 

The `ref.current` object is always mutated directly and the object itself remains stable across multiple renders. The data held in the `ref.current` object is only used in events but not for rendering purpose. 

If `ref.current` changes overtime, putting it in the dependencies of useEffect/useCallback will cause problem, as mutating ref.current doesn't trigger re-rendering and re-run of the hooks.

**Comment by xushicheng** [comment]
Hello @szhsin, thanks for your reply, I don't understand half.

If we want to use the data held in that `ref.current`, what about using empty deps here? eg:
`[mutableState]  => []`
`[menuRef, mutableState] => []`

Because `useCallback` will always read the latest data held in that `ref.current`.

Everything works fine if I remove those things from deps, I don't see any difference, and no bugs either. 

What am I missing???

**Comment by szhsin** [comment]
yes, using empty deps for these two useCallbacks would be exactly the same. They are included in the dep just for silencing the eslint warnings.
``` jsx
const mutableState = stateRef.current;
```
This line is for easy referencing in the two hooks and helping reduce a tiny bit of repetition and minified bundle size :)  (you don't need to worry about that in application code)
