### ISSUE TITLE
can we add key property to the container element?

### ISSUE THREAD

**Issue by bharatpatil** [szhsin/react-menu#532]
For container props can we please add key property? 

I'm getting error as `Warning: Each child in a list should have a unique "key" prop.` If we see the below image, we could see the multiple containers are getting in the body section (using portal=true prop). However react keeps giving the previously mentioned error related to the `key`.

<img width="428" alt="Screenshot 2022-05-27 at 1 57 21 PM" src="https://user-images.githubusercontent.com/604337/170661683-10a314af-f61d-445b-af5b-51ef620c1f6c.png">

https://github.com/szhsin/react-menu/blob/82a4bd94494ee4d5729cbc5527446250f0f27579/src/components/ControlledMenu.js#L153

**Comment by szhsin** [comment]
Hi @bharatpatil , 
I cannot reproduce this issue: https://codesandbox.io/s/react-menu-starter-forked-xjz7v3
Can you please provide an example? Please confirm whether it's something else in your codebase causing the warnings.

**Comment by bharatpatil** [comment]
sure, I'm trying to create a sandbox.

**Comment by bharatpatil** [comment]
Hey @szhsin , apologies for the trouble. It is working fine. Thanks a lot this great library.
