### ISSUE TITLE
Allow custom element to be set as portal target 

### ISSUE THREAD

**Issue by juspky** [szhsin/react-menu#539]
Currently we are only able to create a portal at document.body
`createPortal(menuList, document.body);`
Unfortunately this causes issues for us and we need to put the portal deeper in the html tree.

It would be amazing if we could set a custom element instead.

**Comment by szhsin** [comment]
Hi @juspky , this is a sensible feature and I will add it in the next release. The `portal` prop will be extended to accept a target DOM element and menu will be rendered into the element.
If this doesn't sound like what you're looking for, please feel free to share your thought.

**Comment by juspky** [comment]
Hi @szhsin 

Awesome.
This sounds exactly like what I need, thank you!

**Comment by szhsin** [comment]
Released in [v3.1.0](https://github.com/szhsin/react-menu/releases/tag/v3.1.0). Please see [this example](https://codesandbox.io/s/react-menu-portal-target-boyxv9) for the usage.
