### ISSUE TITLE
I want to hover the menu Sub Menu to get a Menu on the right side

### ISSUE THREAD

**Issue by MichelZiade** [szhsin/react-menu#579]
Hello,

I am trying to do a Side Nav with a Sub Menu when I hover over the Sub Menu I get some sub menu of the sub menu pop to the right.
but the sub menu of the sub menu is a list. I am trying to use : 
 {({ hover }) => (hover ? "test" : "test")}

but it doesnt accept lists.

Any solutions?

Thank you

**Comment by szhsin** [comment]
Issue fixed in [v3.1.2](https://github.com/szhsin/react-menu/releases/tag/v3.1.2)
Example: https://codesandbox.io/s/react-menu-starter-forked-6m6g4x

**Comment by szhsin** [comment]
Please reopen the issue if you still have questions.
