### ISSUE TITLE
Custom icon instead of submenu's arrow?

### ISSUE THREAD

**Issue by furkanmavili** [szhsin/react-menu#6]
Can we pass custom icon component for submenu's arrow icon?

**Comment by szhsin** [comment]
Hi @furkanmavili ,

The default submenu arrow is a CSS pseudo element, therefore you can change it by override the styles.
Please see [an example](https://codesandbox.io/s/submenu-arrow-icon-dwhk9).

If you use an icon component, you can put the icon together with text label into the `label` prop, and also override the default style to remove the original arrow.
