### ISSUE TITLE
Is it possible to create a Handy-Menu?

### ISSUE THREAD

**Issue by frankdema** [szhsin/react-menu#617]
Hi,

Is it possible to create a Handy Menu.

<img width="305" alt="Bildschirmfoto 2022-08-16 um 15 08 42" src="https://user-images.githubusercontent.com/77227123/184887425-1d310a8d-ddee-4905-8709-9aca5fb5a3c9.png">

best with dropdown possibility?

<img width="298" alt="Bildschirmfoto 2022-08-16 um 15 32 39" src="https://user-images.githubusercontent.com/77227123/184892494-0a5e55fd-057e-49f5-bf30-bde28a407b13.png">

I use tailwindcss.

thanks a lot.

**Comment by szhsin** [comment]
Hi @frankdema , if you mean a hamburger menu it's not supported. This libarry implement the [AIRA menu pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu/).

**Comment by frankdema** [comment]
thank you.
