### ISSUE TITLE
Do not close the outer menu on inner menu select

### ISSUE THREAD

**Issue by michalusio** [szhsin/react-menu#649]
React/React-dom version: 16.13.1
React-Menu version: 3.1.2

Hello!

I am not sure if this issur was brought up before- I have checked the issues but nothing came up.

I have a Menu that is a portal and inside of it I have various forms.
A part of those forms are other Menus which work as dropdowns.
What I have noticed is that when the I have the outer menu open and I select something in the inner menu, both of the menus close.

Is there a way to have only the inner menu close?
I am not using submenus, just a Menu in a Menu.

I have tried using `clickEvent`'s `syntheticEvent.stopPropagation()` but it does not work.
What does have some effect is throwing an error in the callback but apart from being ugly it also makes the inner menu stay open too, which is not what I would want.

Thanks in advance for the reply!

**Comment by szhsin** [comment]
Hi @michalusio , you might try to use the [`ControlledMenu`](https://szhsin.github.io/react-menu#controlled-menu) component as the outer menu, and conditionally close menu in the `onClose` event, which has a [close reason](https://github.com/szhsin/react-menu/blob/5c82030070ed4751c5c734f36a3e7c318e69d5b2/types/index.d.ts#L14) field indicating what causes it to close in the event object.

However, I do not encourage you for this approach, as the components are not designed to support nesting one menu inside another menu (expect through the submenu component). Even if it manages to work somehow, there can be other issues down the track. There is some complexity in managing the focus, keyboard interactions between the inner and outer menus.
