### ISSUE TITLE
How to make a click event submenu

### ISSUE THREAD

**Issue by XIIIcool** [szhsin/react-menu#680]
Hello, thanks for a great component.
I need the submenu to work the same as the menu buttons. Is it possible to do this?

**Comment by szhsin** [comment]
Hello @XIIIcool , submenu has a `openTrigger` prop when it is given value 'clickOnly', the submenu will only open in response to click events.

**Comment by XIIIcool** [comment]
But I need to make an onclick event on the submenu so that I can use it as a button, and the child elements open on hover

**Comment by szhsin** [comment]
If you need to listen to the `onClick` event on submenu, you can supply an `onClick` callback to the `itemProps` on submenu: 
```jsx
<SubMenu
  label="Edit"
  itemProps={{ onClick: () => console.log("submenu clicked") }}
>
  <MenuItem>Cut</MenuItem>
  <MenuItem>Copy</MenuItem>
  <MenuItem>Paste</MenuItem>
</SubMenu>
```
All properties of the `itemProps` are forwarded to the submenu item DOM node.

**Comment by XIIIcool** [comment]
thanks a lot
