### ISSUE TITLE
React Components as Menu's Children?

### ISSUE THREAD

**Issue by kaabij** [szhsin/react-menu#7]
Is it possible to have React components that render/return `MenuItem` or `SubMenu` as a child of `Menu` or `ControlledMenu`? For example, if you wanted to apply some logic or special functionality, or just break a very large menu into smaller pieces, how would you approach this?

```javascript
const SomeItems = () => (
  <>
    <MenuItem>New File</MenuItem>
    <MenuItem>Save</MenuItem>
    <MenuItem>Close Window</MenuItem>
  </>
);

...

<ControlledMenu anchorRef={buttonRef} isOpen={open}>
  <SomeItems />
</Controlled Menu>
```

I noticed that you can can bypass the children check by specifying:
```javascript
SomeItems.__name__ = 'MenuItem'
```

Here are more examples:
[code sandbox](https://codesandbox.io/s/react-menu-material-uiname-tfx2u?file=/src/App.js)

**Comment by szhsin** [comment]
Hi @kaabij ,

Menu maintains a current index to keep track of which item is being focused, and each menu item has an index injected for focus navigation among other items using keyboard.
The pattern you mentioned does have some good points, however, there is implementation difficulty.
It's impossible to retrieve the content inside a React component, in your example, the `<MenuItem/>` inside `<SomeItems/>`

There is a workaround that you can have functions which return an array of menu items:
```jsx
const someItems = () => {
    return [
        <MenuItem>New File</MenuItem>,
        <MenuItem>Save</MenuItem>,
        <MenuItem>Close Window</MenuItem>
    ];
}

<Menu menuButton={<MenuButton>Open</MenuButton>}>
    {someItems()}
</Menu>
```

Out of curiosity, I did an experiment with menu components in the [material-ui](https://material-ui.com/components/menus/). 
If I wrap menu items inside a React fragment or component, its key navigation fails as well.
