### ISSUE TITLE
Improvement for useMenuState hook

### ISSUE THREAD

**Issue by panciumihai** [szhsin/react-menu#701]
### Suggestion
Hi @szhsin. Thank you for the last update and this awesome library. After I played with it more I spot a nice improvement that we can add to it in order to have less boilerplate at the end user. This improvement is for the useMenuState hook. Shortly, for my case, I needed a pop-up which can be triggered by a "more options" button or at the right click for the context menu. This behaviour with the current implementation needs 1 ref and one state with the X - Y position. What I did to improve this is to create a custom hook and wrap the useMenuState with it.

```JS
type Point = {
  x: number;
  y: number;
};

const useContextMenu = (options: MenuStateOptions) => {
  const [menuProps, toggleMenu] = useMenuState(options);

  const [anchorPoint, setAnchorPoint] = useState<Point>();
  const anchorRef = useRef<Element | null>(null);

  const setAnchor = useCallback((value: Element | Point | null) => {
    if (value === null) {
      anchorRef.current = null;
      setAnchorPoint(undefined);
      return;
    }

    if (value instanceof Element) {
      anchorRef.current = value;
      setAnchorPoint(undefined);
      return;
    }

    setAnchorPoint(value);
    anchorRef.current = null;
  }, []);

  return [
    { ...menuProps, anchorPoint, anchorRef: anchorRef.current ? anchorRef : undefined },
    toggleMenu,
    setAnchor
  ] as const;
};
```

### Example of use case
```JS
  const [menuProps, toggleMenu, setAnchor] = useContextMenu({ transition: true });

  const moreOptionsClickHandler = useCallback(
    (e: React.MouseEvent, id: string) => {
      setFocusedTimelineId(id);
      setAnchor(e.currentTarget);
      toggleMenu(true);
    },
    [toggleMenu]
  );

  const contextMenuHandler = useCallback(
    (e: React.MouseEvent, id: string) => {
      e.preventDefault();
      setFocusedTimelineId(id);
      setAnchor({ x: e.clientX, y: e.clientY });
      toggleMenu(true);
    },
    [toggleMenu]
  );

  const menuItemClickHandler = useCallback(
    (action: string) => console.log(action, focusedId),
    [focusedId]
  );

  const closeContextMenuHandler = () => {
    toggleMenu(false);
    setFocusedTimelineId("");
  };

return (
<>
  <button ref={setAnchor}>Attach anchor with ref</button>
  <button onClick={(e) => moreOptionsClickHandler(e,123)}>More options</button>
  <div onContextMenu={e => contextMenuHandler(e,123)}>Right click to open context menu</div>
  <ExampleContextMenu
          {...menuProps}
          offsetX={-10}
          offsetY={15}
          align={menuProps.anchorRef ? "end" : "start"}
          onItemClick={e => menuItemClickHandler(e.value)}
          onClose={closeContextMenuHandler}
   />
</>
);
```

### The gains
The main gain here is the easier management of the menu anchor. Also, the end user can give a coordinate or ref as the anchor and the menu will adapt to it. That will lead to less micromanagement from the final user.

I hope you will consider interesting this approach, also if I didn't explain something correctly please let me know and I will try to come up with more details. Thank you again and have a nice week!

**Comment by szhsin** [comment]
Hi @panciumihai ,

Thanks again for your feedback and PR as well.

After assessing the problem and proposed solution, I noticed the following issues:
1. Using a menu as a dropdown and context menu at the same time, and allowing user to dynamically switch between the two is not a day-to-day usage of the library. The use case might not be common enough to warrant an implementation/API within the library itself. This specific case could be easily implemented in the user space if required.
2. From the API perspective, the proposed solution makes the API more coupling and less flexible:
To use the `ControlledMenu` component, two categories of props are needed:
  - state
    - Can be a plain state when menu transition is not needed https://szhsin.github.io/react-menu#managing-state
  *or*
    - `useMenuState`  when transition is needed https://szhsin.github.io/react-menu#use-menu-state
  - anchor 
    - `anchorRef` as a dropdown menu
    *or*
    - `anchorPoint` as a context menu
  These are four APIs which are small and de-coupled and can be freely composable at user's discretion, e.g:

    1. To build a dropdown menu without transition: use a plain state and `anchorRef`
    2. To build a context menu with transition: use `useMenuState` and `anchorPoint`
    3. To build a dropdown/context menu with transition (like your use case): use `useMenuState`, `anchorPoint` and `anchorRef`
    4. ...and more possible combinations of API usage as per user's requirements.

When we design the API for a library, we aim to keep it less coupled and more composable to offer greater flexibility. Composable APIs are also tree-shakable during bundling process. The proposed change in your PR is kind of doing the opposite, it couples three of the four APIs into one hook which forces a user to use both `anchorPoint` and `anchorRef` even if only one is needed in the most cases. 

Hope my writing makes sense and feel free to share your thought if you have any concerns.

**Comment by panciumihai** [comment]
Hi @szhsin,

Yeah, I got your point. In fact, that hook is called useMenuState which handles only the state of the menu. I thought it is a very common use case but it might be not. We can cancel that PR but I think it's worth it to add that custom hook implementation to the documentation. It is useful when you have cards with a context menu and a more options button.

One more thing, don't know exactly if it is a bug. Please let me know if I should write an issue for it. When I used useMenuState({transition: true}). The transition is not working for the submenus of that ControlledMenu, as a fix, I added the transition={true} field on the ControlledMenu.

Thank you for the answer, I'm learning nice things from your library. It's nice structured

**Comment by szhsin** [comment]
I agree it's worth adding the custom hook implementation to the docs. As this is not a common scenario and sometimes might be even a confusing use case, it is best to add a side note to the context menu doc section with a link of a code sandbox example.

Also, I noticed in your example the `ref` is mutated. This is error-prone as mutating ref doesn't cause re-render and updates could get ignored. It might work for you because the `anchorPoint` is also updated which triggers a re-render anyway. 
In addition, the `value instanceof Element` condition checking doesn't work.
Here is an example that works for me: https://codesandbox.io/s/usecontrolledmenu-9u7tol

Regarding your question about `transition`, it is intended as `useMenuState` only has effects on the `ControlledMenu` that uses its return value. Both the `Menu` and `SubMenu` are uncontrolled components (which manages state and transition internally) and the transition option is set using props on the root menu component.

**Comment by panciumihai** [comment]
> 

Yeah, you are right. I use TypeScript for the current project and didn't spot the issue with `value instanceof Element`. I will use your checks instead because they also work for JS. Thank you for the example and the answer about `transition`.
