### ISSUE TITLE
Can not access menuitem ref

### ISSUE THREAD

**Issue by yacinebenkaidali** [szhsin/react-menu#75]

**Comment by szhsin** [comment]
Hi @yacinebenkaidali , thanks for your feedback.

Currently React-Menu doesn't implement `forwardRef`. As React team recommends `forwardRef` be a break change, the feature will not be added until the next major version bump along with other break changes.

Btw, could you give some details about your use case that requires attaching `ref` to the internal DOM element?

**Comment by yacinebenkaidali** [comment]
Hi @szhsin thanks for replying and for this awesome component
My use case is implementing Drag and Drop on menu items
