### ISSUE TITLE
An option to disable auto-focus of the hovered menu item

### ISSUE THREAD

**Issue by Elringus** [szhsin/react-menu#760]
I've seen similar requests, but they were about implementing some kind of input elements inside the menu and the answer was that it's out of scope of the solution which is fair.

In my case however it's not about input. I just need an option to disable the focus when item is hovered, because it breaks UX in context menus (it's not the case with usual/non-context menus).

To give some context, I'm making an IDE/editor PWA where some inputs have context menu and hot keys for the associated actions. Hovering context menu items shouldn't blur the inspected input, as it will both confuse the user (the input for which context menu is opened will no longer be highlighted) and prevent hotkeys from working correctly:

https://user-images.githubusercontent.com/2056864/208300607-e1a71772-e45a-4d1d-bbfe-1bc001c10af2.mp4

I understand that it may be against ARIA best practices, but I believe the standards are not universal and may not apply in some cases. Can you please consider adding an option to disable auto-focus for menu items?

**Comment by szhsin** [comment]
Hi @Elringus ,

I understand there are legitimate use cases where automatically focusing hovered item seems a bit annoying. Currently there are on means to change this behaviour. But a small change can be made to allow the capability. Please follow up the conversation in #761.
