### ISSUE TITLE
Getting warning when used with ssr

### ISSUE THREAD

**Issue by astroanu** [szhsin/react-menu#8]
I'm using this with next js and the following is being printed to the console

`Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
`

Any idea how to remove this?

**Comment by szhsin** [comment]
Hi @astroanu ,

I released a patch in [v1.0.3](https://github.com/szhsin/react-menu/releases/tag/v1.0.3) which should get around the warning.

For more details about this issue, please see [#14927](https://github.com/facebook/react/issues/14927).

You might find [this comment](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85#gistcomment-2911761) useful when testing with Jest.

**Comment by astroanu** [comment]
Thank you. it's working great!
