### ISSUE TITLE
Menu won't update the position when resizing and using direction top

### ISSUE THREAD

**Issue by cinthialandia** [szhsin/react-menu#80]
Hello, I'm using your library and I really like it!

I'm creating a menu with a search field that filters items as seen in [your example](https://szhsin.github.io/react-menu/#focusable-item), except the menu are rendered with a "top" position rather than the default position.

The problem is that, when the items get filtered, the menu doesn't resize correctly so it looks shorter but the position doesn't get updated. 

Here's an example to reproduce my error:

https://stackblitz.com/edit/react-menu-wont-resize-rcrwmg?file=index.tsx

**Comment by szhsin** [comment]
Hi @cinthialandia , thanks for your feedback.
Currently repositioning menu explicitly/automatically when it's open has not been supported. This feature will be added in a future (probably next one) release.

**Comment by szhsin** [comment]
The issue was fixed in [v1.9.0](https://github.com/szhsin/react-menu/releases/tag/v1.9.0).
