### ISSUE TITLE
Only Firefox: triggering toggleMenu, It removes ranges from selected text (as removeAllRanges)

### ISSUE THREAD

**Issue by AleksandrKarashev** [szhsin/react-menu#802]
(using nextjs)
React/React-dom version: 18.2.0
React-Menu version: 3.3.1 and olders

 (the bug exists only in Firefox, Google and Edge are ok)
 
## Describe the bug
triggering toggleMenu, removes ranges from selected text (as `removeAllRanges`)

## To Reproduce

1. select text
2. click on the right button
3. menu will appear, but ranges of selected text will be removed

## Code snippets/CodeSandbox examples/Screenshots

```
  const [menuProps, toggleMenu] = useMenuState();
  const [anchorPoint, setAnchorPoint] = useState({ x: 0, y: 0 });

  return (
    <div
      onContextMenu={(e) => {
        e.preventDefault();
        setAnchorPoint({ x: e.clientX, y: e.clientY });
        toggleMenu(true);
      }}
    >
      Hello World
      <ControlledMenu
        menuClassName={styles.container}
        {...menuProps}
        anchorPoint={anchorPoint}
        onClose={() => toggleMenu(false)}
      ></ControlledMenu>
    </div>
  );
```

**Comment by szhsin** [comment]
Hello @AleksandrKarashev 

The implementation relies on focus to manage keyboard navigation and to close menu when something outside is clicked. It requires moving focus inside menu when the menu is open. This will cause the selected text to lose focus and selection in Firefox.

You may use a workaround which overrides the behaviour and prevents menu from gaining focus with some tradeoffs:
- The keyboard interaction will stop working.
- Menu won't close when something outside of it is clicked. You will need to manually handle it.

[Code sandbox](https://codesandbox.io/s/react-menu-802-4kh9v1)
The example sets `captureFocus={false}` for menu and `tabIndex={undefined}` for menu items.

**Comment by AleksandrKarashev** [comment]
@szhsin, thank you for your quick response  and for your explanation! And especially thansks for your library, it helps me a lot !

**Comment by AleksandrKarashev** [comment]
[szhsin](https://github.com/szhsin), looks like tabIndex={undefined} not working for SubMenu

**Comment by szhsin** [comment]
The `tabIndex` of submenu cannot be overridden currently. I will add a new prop that allows it to be changed. This also unifies the API which sends clear signal to user they are overriding the default behaviour.

**Comment by szhsin** [comment]
Added a new `focusProps` prop in v3.4.0. 
Submenu focus mechanism can be overridden with
```jsx
<SubMenu
  focusProps={{ tabIndex: undefined }}
  itemProps={{ tabIndex: undefined }}
>
```
[CodeSandbox](https://codesandbox.io/s/react-menu-802-4kh9v1)
