### ISSUE TITLE
How to invoke action of a MenuItem when Enter key is pressed

### ISSUE THREAD

**Issue by nik72619c** [szhsin/react-menu#813]
React/React-dom version: latest
React-Menu version: latest

I wish to invoke the function (which is given to `onClick` prop) to also get invoked if I press `Enter` key while on a MenuItem. How can I achieve this?

**Comment by pikapower9080** [comment]
Does it not already do this? It should.

**Comment by nik72619c** [comment]
No it doesnt do it by default. I tried putting a log on the function which is invoked when menuItem is clicked; it only logs if MenuItem is clicked and not if Enter key is pressed on it.

**Comment by szhsin** [comment]
Hi @nik72619c , the onClick event should already be fired for both mouse and keyboard events. Please see this [sandbox example](https://codesandbox.io/s/react-menu-813-cvj7gd?file=/src/App.js).
<img width="691" alt="813" src="https://user-images.githubusercontent.com/41896553/215646655-778231e6-00c9-42e9-85b6-74379209d6f2.png">
