### ISSUE TITLE
New tab links open twice when selected with keyboard navigation

### ISSUE THREAD

**Issue by pikapower9080** [szhsin/react-menu#814]
React/React-dom version: 18.2.0
React-Menu version: 3.1.2

## Describe the bug
When selecting a link, or a menu item with `href` set and target set to `_blank`, in a menu, specifically a context menu in this case, the link opens twice in two new tabs, with a short delay after the first one. The issue does not occur when you click on the link.

## To Reproduce

1. Create a menu and a menu item
2. Give it a valid `href`
3. Set it's `target` to `_blank` so it opens in a new tab
4. Select the link using keyboard navigation and press enter

## Expected behavior
Link should only open once, just like when clicked.

## Code snippets/CodeSandbox examples/Screenshots
```jsx
<MenuItem href={'https://example.com'} target={"_blank"}>Example Link</MenuItem>
```

**Comment by szhsin** [comment]
Fixed in v3.4.1
