### ISSUE TITLE
Bug positioning the menu when using anchorPoint with an arrow.

### ISSUE THREAD

**Issue by AmyAmy** [szhsin/react-menu#820]
React/React-dom version: 17.0.1
React-Menu version: 3.4.1

## Describe the bug
Menu isn't positioned correctly when using an anchorPoint and arrow, but differently depending on the position, making it impossible to compensate for.

## To Reproduce

1. Use an anchorPoint
2. Use an arrow.
3. See what happens when the anchorPoint is near the edge of the screen and when it's not.

## Expected behavior
Arrow points to the anchorPoint both when near the edge of the screen and not.

## Code snippets/CodeSandbox examples/Screenshots

https://codesandbox.io/s/react-menu-dark-theme-forked-elu58x?file=/src/App.js

Not near the edge of the screen.
![image](https://user-images.githubusercontent.com/630387/217294505-31bd47b7-e2f8-44bf-80c6-58f9b2364745.png)

Near the edge of the screen.
![image](https://user-images.githubusercontent.com/630387/217294901-1bd76eb0-a4cf-4568-9689-fa3d2b70906e.png)

```jsx
import { useState } from "react";
import { ControlledMenu, MenuItem, useMenuState } from "@szhsin/react-menu";
import "@szhsin/react-menu/dist/index.css";

export default function Example() {
  const [menuProps, toggleMenu] = useMenuState();
  const [anchorPoint, setAnchorPoint] = useState({ x: 0, y: 0 });

  return (
    <div
      onMouseDown={(e) => {
        e.preventDefault();
        setAnchorPoint({ x: e.clientX, y: e.clientY });
        toggleMenu(true);
      }}
      style={{
        background: "#eee",
        position: "absolute",
        inset: "0"
      }}
    >
      Click to set anchorPoint.
      <div
        style={{
          left: anchorPoint.x,
          top: anchorPoint.y,
          height: "1px",
          width: "1px",
          position: "absolute",
          borderRadius: "50%",
          outline: "red 1px solid",
          outlineOffset: "4px"
        }}
      ></div>
      <ControlledMenu
        {...menuProps}
        arrow
        anchorPoint={anchorPoint}
        direction="top"
        onClose={() => toggleMenu(false)}
      >
        <MenuItem>Item 1</MenuItem>
        <MenuItem>Item 2</MenuItem>
        <MenuItem>Item 3</MenuItem>
      </ControlledMenu>
    </div>
  );
}
```

**Comment by szhsin** [comment]
Hi @AmyAmy , can you try to set a `offsetX` to see if that's what you need? 
``` diff
<ControlledMenu
  {...menuProps}
  arrow
  anchorPoint={anchorPoint}
  direction="top"
+ offsetX={-15}
  onClose={() => toggleMenu(false)}
>
```
[codesandbox](https://codesandbox.io/s/react-menu-dark-theme-forked-fglhm8)

Similarly, if `direction` is 'left' or 'right', `offsetY` prop should be used.

**Comment by AmyAmy** [comment]
That does fix it in the codesandbox, but not in my full app, I'll investigate further.

**Comment by AmyAmy** [comment]
Ok, figured it out: the arrow size is expressed in `rem` in the default CSS, while the offset is in `px`. So there's some minor issues for users overriding the base font-size in their browser. But I can work around that.

Guess it's up to you whether you want to fix that in your components.

**Comment by szhsin** [comment]
Thanks for the updates. Users should be able to figure out a proper offset value.

Like in [this example](https://codesandbox.io/s/react-menu-dark-theme-forked-zs5827?file=/src/App.js), where `font-size` is `2rem` on the root document, we can increase the offset accordingly to compensate for the arrow size.

**Comment by AmyAmy** [comment]
Not exactly what I was talking about, but here is a working example, in case somebody finds this useful:

https://codesandbox.io/s/react-menu-dark-theme-forked-yle22h?file=/src/App.js

`font-size` is _not_ set on the root, so the browser uses the default.
By default this is 16px in all browsers, but specific users may change this, for example for accessibility reasons. _Note that this is not the same as zooming in._

In Firefox: by going to the menu, then **Settings**. On the **General** tab scroll down to **Fonts** and then change the font size.
In Chrome: by going to the menu, then **Settings**. On the **Appearance** tab, click **Customize fonts**. Use the **Font size** slider to change the font size.

You may need to refresh the page to see any changes.

The way around this is by just asking the browser what the current font-size when the menu opens, and keeping track of that with `useState`.
