### ISSUE TITLE
How can I add icon for SubMenu?

### ISSUE THREAD

**Issue by KPreis** [szhsin/react-menu#827]
Hi!

How can I add icon for SubMenu?

React/React-dom version:  8.2.0
React-Menu version: 3.3.1

We need menu with icons. For MenuItems I added icons, but I can't add icon for SubMenu.

Best regards

**Comment by szhsin** [comment]
Hello @KPreis , you can add icon in submenu item with the `label` prop:
```jsx
<SubMenu
  label={
    <>
      Actions <YourIcon />
    </>
  }
>
  <MenuItem>Item 1</MenuItem>
  <MenuItem>Item 1</MenuItem>
</SubMenu>
```
The `label` prop accepts any valid jsx.

**Comment by KPreis** [comment]
Thank you!
