### ISSUE TITLE
MenuList container is always rendered

### ISSUE THREAD

**Issue by bozdoz** [szhsin/react-menu#85]
Just noticing that the menu container is always rendered:

https://github.com/szhsin/react-menu/blob/206c5693b6a41c137a53f6d08e1ad8a8eb5ee3f8/src/components/useMenuList.js#L93-L109

I was wondering if the presentation container could be rendered only when open: similar to the menu list itself. Not sure if it is on purpose or not.

**Comment by szhsin** [comment]
Hi @bozdoz , this is a good point. Sometimes design decision was made and reason get forgot.
I think it's probably because the container (parent) needs to render before the menu list (child), otherwise when effects (for positioning menu) in the menu list run, the container is still `null`.

**Comment by bozdoz** [comment]
my current use case is a button group which has rounded borders (using css for last-child).  The last item is a Menu though, and it renders the empty, hidden presentational menu beside it (making the last-child selector not work on the button).  As a solution I thought I could set `portal` to `true`, but from my tests `portal` doesn't always seem to work in IE11. FYI

**Comment by szhsin** [comment]
If you have a group of buttons, `button:last-of-type` might work for the case.
