### ISSUE TITLE
Tooltip does not appear on SubMenu

### ISSUE THREAD

**Issue by pi-over-two** [szhsin/react-menu#852]
React/React-dom version: 17.0.2 / 17.0.2
React-Menu version: 3.4.1

## Describe the bug
First, thank you for such a great library! The issue is that SubMenu don't display their tooltip (title); in our app, we have a requirement to show a tooltip on menu items as well as submenu items.

## To Reproduce
1. Make sure SubMenu has a title attribute (tooltip)
2. Click on SubMenu
3. Tooltip does not display over SubMenu

## Expected behavior
Tooltip should display on SubMenu.

**Comment by szhsin** [comment]
I guess you add title prop to the `SubMenu` component itself. This will apply title to the `ul` menu list element. To set title on submenu items, you can use the `itemProps`.

```jsx
<SubMenu label="Edit" itemProps={{ title: "edit" }}>
  <MenuItem>Cut</MenuItem>
  <MenuItem>Copy</MenuItem>
  <MenuItem>Paste</MenuItem>
</SubMenu>
```

**Comment by pi-over-two** [comment]
That was it! Thanks for the prompt response!!
