### ISSUE TITLE
How to get the element in the list that trigger the context menu?

### ISSUE THREAD

**Issue by gdandrewhuang** [szhsin/react-menu#853]
add context menu to each item in the list,
How can get the element that triggers the context menu?
thanks

**Comment by gdandrewhuang** [comment]
syntheticEvent.target

**Comment by gdandrewhuang** [comment]
syntheticEvent.target is menuitem

**Comment by szhsin** [comment]
Hi @gdandrewhuang , can you please give more details about the issue? Is the list a ListView-like component in your project, or is it a menu list? Please provide some example code so I can help.

**Comment by gdandrewhuang** [comment]
thanks, @szhsin please see the demo:
[Demo in codesandbox.io](https://codesandbox.io/s/admiring-rubin-m139nd)

**Comment by szhsin** [comment]
You can store the item in a ref when opening the context menu and use it later:
```jsx
const item = useRef();
<li
  onContextMenu={(e) => {
    item.current = e.currentTarget;
  }}
>
```
Here updated [your example](https://codesandbox.io/s/quizzical-neco-skv6vw).

**Comment by gdandrewhuang** [comment]
thank you very much, @szhsin  this is my want
