### ISSUE TITLE
How do I make sure the focus stays even if I move my mouse cursor away from input box

### ISSUE THREAD

**Issue by devcer** [szhsin/react-menu#882]
React/React-dom version: 18.2.0/18.2.0
React-Menu version: 3.5.2

I have an input box inside a MenuItem(not using FocusableItem). However when I move my mouse around away from the input box, it looses focus. Is there any way to keep focus on the input box even when i move my mouse pointer away from input box? 
I see this is happening in the focusable item example as well but no instructions to disable this behaviour in the document.
* https://szhsin.github.io/react-menu#focusable-item

**Comment by devcer** [comment]
I'm using controlledMenu with MenuItem here

**Comment by devcer** [comment]
Lets assume, I moved to FocusableItem. The focus is removed as soon as I move away from `input`. Is there any way I can keep the focus intact?

Codesandbox: https://codesandbox.io/s/menu-item-57urj8?file=/src/App.js

**Comment by devcer** [comment]
I was able to fix this by placing other MenuItems inside the same FocusableItem. a hack for now but could not find any other solution.

**Comment by szhsin** [comment]
To give more context about the issue, we don't officially support this use case. Please check out [this post](https://github.com/szhsin/react-menu/issues/618#issuecomment-1217968495) for the the rationale behind it.

However, you can override the default behaviour by setting `tabIndex={undefined}` on a menu item which makes the item not focusable. Here is a [sandbox example](https://codesandbox.io/s/react-menu-starter-forked-obywb4?file=/src/App.js:1363-1437).
