### ISSUE TITLE
Is there a way to autofocus on focusable item as soon as the menu is open?

### ISSUE THREAD

**Issue by devcer** [szhsin/react-menu#883]
React/React-dom version: 18.2.0/18.2.0
React-Menu version: 3.5.2

Currently the item is focused only when the mouse it moved over the `FocusableItem`. is there any way to force open the item as soon as the dropdown is opened? because I want to start typing as soon as the dropdown is opened instead of moving my mouse over it and then start typing.

**Comment by szhsin** [comment]
You can provide menu with a `menuItemFocus` prop that indicates which item should receive focus once menu is open.

Assuming you use `ControlledMenu`, here is a [sandbox example](https://codesandbox.io/s/react-menu-starter-forked-hv19mw?file=/src/App.js).

**Comment by devcer** [comment]
Thank you so much! I used a hack temperorily by using `ref` inside focusable item but I'm able to solve it using menuItemFocus.
