### ISSUE TITLE
Feature Request: Support more aria attributes on MeunItem

### ISSUE THREAD

**Issue by isanchen** [szhsin/react-menu#9]
Hi,

First of all, great job and thanks for sharing the component.

We're looking for something with good accessibility and this is wonderful out of the box.

What we would like to see is that all `aria-*` attributes to be supported in the interactive elements in this repo.

For example, if a menu item opens up a dialog, we'd like to add `aria-haspopup="dialog"` to the `MenuItem`'s `<li>`.

A quick and dirty way to support this would be spreading `restProps` on the `<li>` on [this line](https://github.com/szhsin/react-menu/blob/master/src/components/MenuItem.js#L135).

e.g.
```
<li {...restProps} {...menuItemProps}>
```

same as you did [here](https://github.com/szhsin/react-menu/blob/master/src/components/MenuItem.js#L128) but on the `<a>`.

So that consumers can pass arbitrary props via `MenuItem`'s prop interface.

Thanks for considering!

**Comment by szhsin** [comment]
Hi @isanchen ,

Thanks for your feedback on the project. I think it's a very good feature to support and will be added in the coming release.

**Comment by szhsin** [comment]
The feature was released in [v1.1.0](https://github.com/szhsin/react-menu/releases/tag/v1.1.0). @isanchen

**Comment by isanchen** [comment]
Thanks so much @szhsin ! Looking forward to adapt this change in our codebase soon!
