### ISSUE TITLE
ref in FocusableItem is null

### ISSUE THREAD

**Issue by priyankalad** [szhsin/react-menu#902]
React/React-dom version:18.0.0
React-Menu version:3.5.2

## Describe the bug
I've created a menu where I have wrapped a react-router Link inside FocusableItem. 
FocusableItem passes down ref which I further pass to my Link menu item, so that it becomes focusable
ref is coming as **{current: null}**
On focus of  menuitem, the app crashes giving the error "focusRef.current.focus is not a function"

I have also tried a button instead of Link, but it didn't work either.

## Expected behavior
I think if ref has a valid value, then component inside FocusableItem will become focusable.

## Code snippets/CodeSandbox examples/Screenshots
Here's my code
```
<FocusableItem>
            {({ ref, closeMenu }) =>
            <Link to={option.href || '/0/myhome'}>text </Link>
            }
</FocusableItem>
```

**Comment by szhsin** [comment]
Hi @priyankalad , please help me check a few things:
- Has the `ref` been assigned to the `<Link/>` component?
```jsx
<FocusableItem>
  {({ ref, closeMenu }) => (
    <Link ref={ref} />
      text
    </Link>
  )}
</FocusableItem>;
```
- Does the `<Link/>`  component actually forward `ref` to the DOM element which is supposed to receive focus?

Here is a working [example](https://codesandbox.io/s/react-menu-react-router-example-dw4ku?file=/App.js:1079-1424) with react-router.

**Comment by priyankalad** [comment]
@szhsin  Thank you for checking out the issue :)
1. Here the Link is not any custom component, its from react-router-dom
2. I do not understand by "Does the <Link/> component actually forward ref to the DOM element" as Link is the component of react-router-dom.

I will create a sandbox example and try to reproduce this issue.

**Comment by szhsin** [comment]
> I do not understand by "Does the component actually forward ref to the DOM element" as Link is the component of react-router-dom.

I mean the `Link` component needs to use [React forward ref API](https://react.dev/reference/react/forwardRef#render-function) to attach ref to the `<a/>` tag. The `Link` component from _react-router_ already does it so it should be fine.

Here is [another example](https://codesandbox.io/s/react-menu-router-v6-wxi1uf) integrating with the latest react-router version (v6).

**Comment by priyankalad** [comment]
It is working now.
The issue was the version of react-router-dom
Earlier it was   "react-router-dom": "^4.1.2",
And now upgraded I've upgraded it  to "^5.0.0"
 
 Thank you so much @szhsin for your help! :)
