### ISSUE TITLE
Checkbox or Radio button not showing the state when custom style is used

### ISSUE THREAD

**Issue by seperman** [szhsin/react-menu#975]
Hello,
I used the example you provided for custom styling using `@emotion/styled`
When it comes to Radio buttons and Checkboxes, it is not showing the current state which in this case should have been "Advanced".
![Screenshot from 2023-06-14 13-16-07](https://github.com/szhsin/react-menu/assets/2314797/db55e720-534a-4564-a29d-5716d9229dfa)

Also when I hover the mouse over the radio button, it disappears:

![Screenshot from 2023-06-14 13-16-26](https://github.com/szhsin/react-menu/assets/2314797/be3c8b61-0881-41bf-b6eb-1e32b4f9e8e7)

I tried to use:

```
  ${menuItemSelector.typeCheckbox} {
    appearance: checkbox;
    color: black;
  }
```

but that didn't help.

Thanks for your help!

React/React-dom version:17.0.2
React-Menu version:4.0.0

**Comment by szhsin** [comment]
Hi @seperman , the small circles in menu items of your screenshot are default list item style from browsers which should be reset: 
```js
${radioGroupSelector.name} {
  list-style: none;
  padding: 0;
}
```
Menu items are completly unstyled by default, and there aren't any ticks or circles in checkbox and radio items. Here is a [sandbox example](https://codesandbox.io/s/react-menu-emotion-styled-forked-j5x9jh?file=/src/App.js) that adds ticks/circles using css pseudo elements.

**Comment by seperman** [comment]
@szhsin Fantastic! Thank you.
