### ISSUE TITLE
menu closing state

### ISSUE THREAD

**Issue by Faraday26** [szhsin/react-menu#988]
If I click on the submenu it closes the parent menu. Any way not to do that?

**Comment by szhsin** [comment]
You can set the `keepOpen` prop on the event object of onClick/onItemClick to prevent a menu from closing.

Here is a [sandbox example](https://codesandbox.io/s/react-menu-starter-forked-9nxcv5?file=/src/App.js), try to click "Paste" item in the submenu.

You can also do it for all items in the menu by setting `keepOpen` in `onItemClick` event on the root menu.
