### ISSUE TITLE
generate szhsin Menu with menuItems and subMenu from a json data 

### ISSUE THREAD

**Issue by BenmoussaYounes** [szhsin/react-menu#992]
This an Example of my json Data format
 var data = [
  {
    id: "0",
    name: "add",
  },
  {
    id: "1",
    name: "edit",
  },
  {
    id: "2",
    name: "save",
    children: [
      {
        id: "20",
        name: "pdf",
        children: [
          {
            id: "200",
            name: "pdfV1",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "upload",
  },
];
I need a react js dynamic function that generates a szhsin menu with the right submenu or menuItems from a json data like the one up, I know this might be not an issue but I will really appreciate if you can you help

**Comment by szhsin** [comment]
Hello @BenmoussaYounes , with the provided data schema you may use a recursive function to generate menu items and submenus. Here is [an example](https://codesandbox.io/s/react-menu-992-j5njyn?file=/src/App.js).

**Comment by BenmoussaYounes** [comment]
It works, Thank you so much you saved me 💯
